"""Classify doc_census.json rows into DELETE / UPDATE / REVIEW / KEEP and write DELETE_CANDIDATES.md.
Usage: python3 doc_census.py doc_census.json && python3 build_report.py doc_census.json"""
import json, sys, os, subprocess
from collections import defaultdict
rows = json.load(open(sys.argv[1]))
HIST = ('docs/archive/', 'docs/superpowers/', 'docs/handoff/', 'docs/plans/', 'docs/release_candidates/', 'docs/marketing/')
DUPES = {'docs/PIPELINE_OPERATIONS_README.md': 'scripts/PIPELINE_OPERATIONS_README.md (newer, 2026-09-10; code comments point at the scripts/ copy)',
         'docs/PIPELINE_MAINTENANCE_SCHEDULE.md': 'scripts/PIPELINE_MAINTENANCE_SCHEDULE.md (newer copy)'}
ROOT_PLANS = {'SUPP_TYPE_CONSOLIDATION_PLAN.md'}
STALE_WORDS = ('superseded', 'deprecated', 'obsolete', 'retired', 'replaced by', 'outdated', 'out of date', 'historical', 'archived')

def tier(r):
    p = r['path']; total = r['refs'] + r['syms']; dead = r['dead_refs'] + r['dead_syms']; live = r['live_inbound']
    marked = ': status line says ' + ','.join(r['markers']) if r['markers'] else ''
    if p in ('AGENTS.md', 'CLAUDE.md', 'README.md') or p.startswith(('.claude/', 'docs/adr/', 'docs/runbooks/', 'scripts/data/')):
        return 'KEEP', 'constitution / ADR / runbook / skill / data note'
    if p in DUPES: return 'DELETE', 'older duplicate of ' + DUPES[p]
    if p.startswith(HIST): return 'DELETE', 'history dir; git keeps it' + marked
    if '/' not in p and p in ROOT_PLANS: return 'DELETE', 'finished root-level plan' + marked
    if p.startswith('scripts/audits/'):
        if p.startswith(('scripts/audits/pending_items_20260926/', 'scripts/audits/prompts/')): return 'KEEP', 'open register / reusable prompt'
        if live: return 'KEEP', 'audit artifact named by live code or a skill'
        if any(m in r['markers'] for m in STALE_WORDS): return 'DELETE', 'closed audit' + marked
        if r['last'] < '2026-08-01': return 'DELETE', f"closed audit, no live pointer, untouched since {r['last']}"
        return 'REVIEW', f"recent audit ({r['last']}), no live pointer: keep while its register item is open"
    if any(m in r['markers'] for m in STALE_WORDS): return ('UPDATE' if live else 'DELETE'), 'self-marked' + marked
    if total >= 3 and dead / max(1, total) >= 0.25: return 'UPDATE', f"{dead}/{total} named files or symbols no longer exist"
    if not live and r['doc_inbound'] == 0 and r['last'] < '2026-07-01': return 'REVIEW', f"orphan: nothing links to it, untouched since {r['last']}"
    return 'KEEP', 'current; no drift found'

for r in rows: r['tier'], r['why'] = tier(r)
by = defaultdict(list)
for r in rows: by[r['tier']].append(r)
counts = {k: len(by.get(k, [])) for k in ('DELETE', 'UPDATE', 'REVIEW', 'KEEP')}
head = subprocess.run(['git', 'rev-parse', '--short', 'HEAD'], capture_output=True, text=True).stdout.strip()
fix = lambda r: ', '.join(f'`{g}`' for g in r['live_inbound'][:4]) + (' …' if len(r['live_inbound']) > 4 else '')
out = ['# Doc census 2026-09-28: what to delete, update, keep\n',
       f'Generated by `doc_census.py` + `build_report.py` in this folder at HEAD {head}. Truth order: code first; a doc that contradicts '
       'code is a defect (AGENTS.md "Truth order"). git keeps every deleted file, so deletion loses nothing except confusion.\n',
       f'Method: every tracked `.md`/`.txt` outside data dumps ({len(rows)} files). For each: last commit date; every file path and '
       '`symbol()` it names, checked against the tree and the Python def/class table; inbound pointers from live files (AGENTS/CLAUDE/README/'
       'GLOSSARY, `.claude/rules`, `.claude/skills`, any `.py`/`.sh`), path-aware for generic names like README.md; and a stale word on a '
       '`Status:` line or in the first three lines. A "fix pointer" is a live file that names the doc and must change in the same commit '
       'that deletes it.\n',
       '| Tier | Files |\n|---|---|\n' + '\n'.join(f'| {k} | {v} |' for k, v in counts.items()) + '\n',
       f"## DELETE ({counts['DELETE']})\n\nSean decides; nothing has been removed. Grouped by directory.\n"]
groups = defaultdict(list)
for r in by['DELETE']:
    parts = r['path'].split('/')
    groups['/'.join(parts[:2]) if len(parts) >= 3 and parts[0] in ('docs', 'scripts') else (parts[0] if len(parts) >= 2 else '(root)')].append(r)
for g in sorted(groups):
    out.append(f'### {g} ({len(groups[g])})\n\n| Path | Last commit | Why | Fix pointer |\n|---|---|---|---|')
    out += [f"| `{r['path']}` | {r['last']} | {r['why']} | {fix(r)} |" for r in sorted(groups[g], key=lambda r: r['path'])]
    out.append('')
out.append('### Delete in one commit\n\n```bash\ngit rm -q \\\n' + ' \\\n'.join(f"  '{r['path']}'" for r in sorted(by['DELETE'], key=lambda r: r['path'])) + '\n```\n')
out.append(f"## UPDATE ({counts['UPDATE']}): keep, but they name things the code no longer has\n\n| Path | Last commit | Why | Missing names (first 6) |\n|---|---|---|---|")
out += [f"| `{r['path']}` | {r['last']} | {r['why']} | {', '.join('`'+x+'`' for x in (r['dead_list'] + r['dead_sym_list'])[:6])} |" for r in sorted(by['UPDATE'], key=lambda r: r['path'])]
out.append(f"\n## REVIEW ({counts['REVIEW']}): audits newer than August with no pointer, and orphans\n\n| Path | Last commit | Why |\n|---|---|---|")
out += [f"| `{r['path']}` | {r['last']} | {r['why']} |" for r in sorted(by['REVIEW'], key=lambda r: r['path'])]
out.append(f"\n## KEEP ({counts['KEEP']})\n\nConstitution, ADRs, runbooks, skills, rules, `scripts/data` notes, and audit artifacts that live code or a skill names. Full list in `doc_census.json` (`tier` field).\n")
open(os.path.join(os.path.dirname(sys.argv[1]), 'DELETE_CANDIDATES.md'), 'w').write('\n'.join(out))
json.dump(rows, open(sys.argv[1], 'w'), indent=1)
print(counts); print('DELETE groups:', {g: len(v) for g, v in sorted(groups.items())})
print('UPDATE:', [r['path'] for r in by['UPDATE']])
