"""Pipeline-controlled generation of the Flutter medication-depletions artifact
(B1.2 P2). Unlike the byte-copied RDA/UL + product-type vocab, this asset is
GENERATED by the versioned artifact builder and written into Flutter; parity is
verified on content (content_hash + entries), ignoring the release stamp.
"""

import json

import pytest

from sync_flutter_reference_data import (
    DEPLETIONS_DESTINATION_RELATIVE_PATH,
    sync_medication_depletions,
    validate_flutter_medication_depletions,
)


def _source_file(tmp_path):
    src = tmp_path / "medication_depletions.json"
    src.write_text(
        json.dumps(
            {
                "_metadata": {"schema_version": "5.3.0"},
                "depletions": [
                    {
                        "id": "DEP_STATINS_COQ10",
                        "drug_ref": {
                            "type": "class",
                            "id": "class:statins",
                            "display_name": "Statins",
                        },
                        "depleted_nutrient": {
                            "standard_name": "CoQ10",
                            "canonical_id": "coenzyme_q10",
                        },
                        "depletion_type": "depletion",
                        "severity": "significant",
                    }
                ],
            }
        ),
        encoding="utf-8",
    )
    return src


def _repo(tmp_path):
    repo = tmp_path / "app"
    repo.mkdir()
    return repo


def test_sync_writes_versioned_generated_artifact(tmp_path):
    src = _source_file(tmp_path)
    repo = _repo(tmp_path)
    result = sync_medication_depletions(
        source_path=src, flutter_repo=repo, content_version="2026.07.23"
    )
    dest = repo / DEPLETIONS_DESTINATION_RELATIVE_PATH
    assert dest.is_file()
    art = json.loads(dest.read_text(encoding="utf-8"))
    assert art["_metadata"]["content_hash"].startswith("sha256:")
    assert art["_metadata"]["content_version"] == "2026.07.23"
    assert art["_metadata"]["minimum_runtime_contract"] == 1
    assert art["depletions"][0]["citation_review_status"] == "unverified"
    assert result["minimum_runtime_contract"] == 1


def test_validate_passes_on_a_freshly_synced_copy(tmp_path):
    src = _source_file(tmp_path)
    repo = _repo(tmp_path)
    sync_medication_depletions(source_path=src, flutter_repo=repo, content_version="v1")
    # A later validate uses a different release stamp but the same content.
    validate_flutter_medication_depletions(source_path=src, flutter_repo=repo)


def test_validate_detects_tampered_entries(tmp_path):
    src = _source_file(tmp_path)
    repo = _repo(tmp_path)
    sync_medication_depletions(source_path=src, flutter_repo=repo, content_version="v")
    dest = repo / DEPLETIONS_DESTINATION_RELATIVE_PATH
    art = json.loads(dest.read_text(encoding="utf-8"))
    art["depletions"][0]["severity"] = "mild"  # tamper without re-stamping the hash
    dest.write_text(json.dumps(art), encoding="utf-8")
    with pytest.raises(ValueError):
        validate_flutter_medication_depletions(source_path=src, flutter_repo=repo)


def test_validate_requires_versioned_metadata(tmp_path):
    src = _source_file(tmp_path)
    repo = _repo(tmp_path)
    dest = repo / DEPLETIONS_DESTINATION_RELATIVE_PATH
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(json.dumps({"depletions": []}), encoding="utf-8")
    with pytest.raises(ValueError):
        validate_flutter_medication_depletions(source_path=src, flutter_repo=repo)
