import os
import sys

import pytest

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from enhanced_normalizer import EnhancedDSLDNormalizer


@pytest.fixture(scope="module")
def normalizer():
    return EnhancedDSLDNormalizer()


@pytest.mark.parametrize(
    "name,expected_substring",
    [
        ("Magtein Magnesium L-Threonate", "Magnesium"),
        ("NIAGEN Nicotinamide Riboside", "Nicotinamide Riboside"),
        ("N-Acetyl L-Cysteine", "N-Acetyl Cysteine"),
        ("Glucosamine Sulfate 2KCI", "Glucosamine"),
        ("Glucosamine Sulfate 2NaCl", "Glucosamine"),
        ("Pylopass Lactobacillus reuteri", "Lactobacillus Reuteri"),
        ("Bitter Orange Citrus Bioflavonoids", "Citrus Bioflavonoids"),
        ("Pancreatin 4X", "Digestive Enzymes"),
        ("Pancreatin 8X", "Digestive Enzymes"),
        ("Pancrelipase", "Digestive Enzymes"),
        ("Immunoglobulin G", "Immunoglobulin"),
        ("Grape seed ext.", "Grape Seed Extract"),
        ("Guggul Gum Extract", "Guggul"),
        ("S-Adenosyl Methionine", "SAMe"),
        ("S-Adenosylmethionine Tosylate", "SAMe"),
        ("Betain HCl", "TMG"),
        ("sodium hyaluronate", "Hyaluronic Acid"),
        ("melatonin, micronized", "Melatonin"),
        ("Phase 2 White Kidney (bean) extract", "Common Bean Extract"),
        ("Red Sockeye Salmon Oil, Natural, Wild", "Fish Oil"),
        ("cold pressed omega rich Flax seed Oil", "Flaxseed"),
        ("Ashwagandha Leaf, Root Extract", "Ashwagandha"),
        ("Dairy Digestive Enymes", "Digestive Enzymes"),
        ("TeaSlender Green Tea Phytosome", "Green Tea Extract"),
        ("Oligopin French Maritime Pine (Pinus pinaster) extract", "Pine Bark Extract"),
        ("Wellmune WGP", "Beta-Glucan"),
        ("Bioferrin", "Lactoferrin"),
        ("Beta-Glucanase", "Digestive Enzymes"),
        ("Siberian Eleuthero", "Ginseng"),
        ("Phosphatidyl L-Serine", "Phosphatidylserine"),
        ("M.S.M.", "MSM"),
        ("Para-Amino Benzoic Acid", "PABA"),
        ("Ginkgold Ginkgo biloba extract", "Ginkgo"),
        ("Chaste extract", "Chasteberry"),
        ("Testofen Fenugreek seed extract", "Fenugreek"),
        ("Beta 1,3 Glucan", "Beta-Glucan"),
        ("Rutin (Sophora japonica) flower bud extract", "Citrus Bioflavonoids"),
        ("S-Acetyl-L-Glutathione", "Glutathione"),
        ("Carnipure L-Carnitine", "L-Carnitine"),
        ("Black Cohosh (Cimicifuga racemosa) root and rhizome extract", "Black Cohosh"),
        ("Icelandic Kelp", "Iodine"),
        ("L-Lysine Monohydrochloride", "L-Lysine"),
        ("Boron Amino Acid Chelate", "Boron"),
        ("Glucosamine Sulphate 2KCl", "Glucosamine"),
        ("isolated Soy Protein", "Protein"),
        ("Soy Protein isolate", "Protein"),
        ("L-Cysteine/N-Acetyl L-Cysteine", "N-Acetyl Cysteine"),
        ("Alpha-Lipoic Acid & R-Lipoic Acid", "Alpha Lipoic Acid"),
        ("Niacinamide/Niacin", "Vitamin B3"),
        ("dried Ferrous Sulfate", "Iron"),
        ("Joint Shield 5-Loxin Advanced Boswellia serrata extract", "Boswellia"),
        ("Mixed Bioflavonoids", "Citrus Bioflavonoids"),
        ("Sensoril Ashwagandha root & leaf extract", "Ashwagandha"),
        ("Vitamin K1/K2", "Vitamin K"),
        ("DL-Alpha Tocopheryl Acetate", "Vitamin E"),
        ("S. cerevisiae", "S. cerevisiae"),
        ("Pituitary", "Pituitary"),
        ("Kidney", "Kidney"),
        ("Pancreas", "Pancreas"),
        ("Heart", "Heart"),
        ("Ovary", "Ovary"),
        ("Hypericins", "St. John's Wort"),
        ("Andrographis aerial parts extract", "Andrographis"),
        ("Horehound", "Horehound"),
        ("Wheat Grass/Barley Grass", "Wheat Grass/Barley Grass"),
        ("Oyster extract", "oyster extract"),
        ("Synapsa", "Bacopa"),
        ("NovaSoy", "Isoflavones"),
        ("CardioAid Plant Sterols", "Phytosterols"),
        ("Hesperidin Bioflavonoid extract", "Citrus Bioflavonoids"),
        ("Bifidobacterium breve", "Bifidobacterium Breve"),
        ("Selenium AAC", "Selenium"),
        ("Zinc Mono-L-Methionine Sulfate", "Zinc"),
        ("Pau D’Arco bark extract", "Pau D'Arco"),
        ("Ginkgo biloba 50:1 leaf extract", "Ginkgo"),
        ("Rhodiola (Rhodiola rosea L.) rhizome extract", "Rhodiola"),
        ("Aloe vera leaf gel 200:1 extract", "Aloe Vera"),
        ("Hawthorn 1.8% extract", "Hawthorn"),
        ("Calcium-Magnesium Inositol Hexaphosphate", "Inositol Hexaphosphate"),
        ("Boswellin Super (Boswellia serrata) gum resin extract", "Boswellia"),
        ("Lactobacillus acidophilus L-92", "Lactobacillus Acidophilus"),
        ("N-Acetyl-L-Cysteine/L-Cysteine HCl", "N-Acetyl Cysteine"),
        ("Vanadium Amino Acid Chelate", "Vanadyl Sulfate"),
        ("Pancreatic Enzymes 11x", "Digestive Enzymes"),
        ("Sharp-PS Gold Conjugated PS-DHA", "Phosphatidylserine"),
        ("Coptis (Coptis chinensis) root & rhizome 12:1 extract", "Coptis Rhizome"),
        ("Coriolus (Coriolus versicolor) fruiting body extract", "Kawaratake"),
        ("Artist's Conk", "Artist's Conk"),
        ("Fringe Tree (Chionanthus virginicus) bark extract", "Fringe Tree"),
        ("Lobelia", "Lobelia"),
        ("Quassia", "Quassinoids"),
        ("Horseradish", "Horseradish"),
        ("Actazin Kiwifruit Powder", "Kiwifruit"),
        ("Tillandsia", "Tillandsia"),
        ("Selenium Chelate", "Selenium"),
        ("Horny Goat Weed P.E.", "Icariin"),
        ("Cholesstrinol HP", "Phytosterols"),
        ("Willow bark 5:1 extract", "White Willow Bark"),
        ("Sprouted Barley Juice", "Barley Juice"),
        ("Beta Zea Carotene", "Vitamin A"),
        ("Rennin", "Digestive Enzymes"),
        ("SesaPlex Sesame seed extract", "Sesamin"),
        ("Yucca juice extract", "Yucca"),
        ("Indian Madder", "Indian Madder"),
        ("Oregon Grape (Berberis aquifolium) root 4:1 extract", "Oregon Grape"),
        ("Hops (Humulus lupulus L.) cone 7.5:1 extract", "Hops"),
        ("KSM-66 organic Ashwagandha root extract", "Ashwagandha"),
        ("Ashwagandha (Sensoril brand) root and leaf extract", "Ashwagandha"),
        ("Ashwaganda", "Ashwagandha"),
        ("Citicoline Cognizin brand", "Choline"),
        ("Rhodiola rosea 3% extract", "Rhodiola"),
        ("Panax ginseng 7% extract", "Ginseng"),
        ("Milk Thistle 80% extract", "Milk Thistle"),
        ("St. John's Wort Whole Herb Extract", "St. John's Wort"),
        ("Vitex Berry Extract", "Chasteberry"),
        ("L-Citrulline Hydrochloride", "L-Citrulline"),
        ("Calcium Alpha-Ketoglutarate", "Alpha-Ketoglutarate"),
        ("L-methyfolate", "Vitamin B9"),
        ("Ferrochel Iron Bisglycinate", "Iron"),
        ("OptiMSM Methylsulfonylmethane", "MSM"),
        ("Long Jack", "Tongkat Ali"),
        ("Tongkat Ali 50:1 extract", "Tongkat Ali"),
        ("Boswellia serrata dried extract", "Boswellia"),
        ("AprèsFlex Boswellia serrata", "Boswellia"),
        ("Cellulase Enzymes", "Digestive Enzymes"),
        ("L-Cysteine and N-Acetyl L-Cysteine", "N-Acetyl Cysteine"),
        ("Epigallocatechin 3-Gallate", "Egcg"),
        ("Chromium chromaX(R)", "Chromium"),
        ("PrimaVie purified Shilajit", "Shilajit"),
        ("Safr'Inside", "Saffron"),
        ("Whole Glucan Particle", "Beta-Glucan"),
        ("Guggul lipids powder", "Guggul"),
        ("L-Dihydroxyphenylalanine", "L-Dopa"),
        ("Diadzein", "Daidzein"),
        ("North Atlantic Kelp", "Brown Kelp"),
        ("Blueberry, Wild", "Blueberry"),
        ("L-Alpha-Glycerylphosphorylcholine", "Alpha GPC"),
        ("Isatis", "Woad"),
        ("Pycrinil Artichoke (Cynara cardunculus) leaf extract", "Globe Artichoke"),
        ("Alfalfa (Medicago sativa) aerial part extract", "Alfalfa"),
        ("Ivy extract", "Ivy"),
        ("Parsley herb powder", "Parsley"),
        ("Pumpkin seed meal powder", "Pumpkin"),
        ("Goldenrod Powder", "Goldenrod"),
        ("Cassava", "Cassava"),
        ("Acai Berry Fruit Extract", "Acai"),
        ("Oat 10:1 extract", "Oat Straw"),
        ("Oat Beta Glucan Concentrate", "Beta-Glucan"),
        ("Horsetail aerial parts ext.", "Horsetail"),
        ("MirtoSelect Bilberry", "Bilberry"),
        ("Pycnogenol French Maritime Pine", "Pine Bark Extract"),
        ("Integra-Lean African Mango", "African Mango"),
        ("NT2 Collagen", "Collagen"),
        ("Lemon Grass", "Lemongrass"),
        ("Lithothamnion corallioides", "Calcium"),
        ("Orange Pekoe (Camellia sinensis) extract", "Black Tea Leaf"),
        ("Maitake (Grifola frondosa) fruit body powder", "Maitake"),
        ("narrow-leaved Coneflower (Echinacea angustifoliae) root extract", "Echinacea"),
        ("Velvet Elk Antler powder", "Deer Antler Velvet"),
        ("Vitamin K2-7", "Vitamin K"),
        ("MenaQ7 Vitamin K2", "Vitamin K"),
        ("Quatrefolic (6S)-5-Methyltetrahydrofolate, Glucosamine Salt", "Vitamin B9"),
        ("Quatrefolic (6S)-5-Methyltetrahydrofolic Acid Glucosamine Salt", "Vitamin B9"),
        ("(6S)-N5-Methyltetrahydrofolic Acid Calcium Salt", "Vitamin B9"),
        ("Magnesium Malate Trihydrate", "Magnesium"),
        ("N-Acetyl L-Carnitine Hydrochloride", "L-Carnitine"),
        ("Molybdenum Citrate", "Molybdenum"),
        ("Ferrous Fumarate Anhydrous", "Iron"),
        ("DeltaGold(TM) Tocotrienol", "Vitamin E"),
        ("Nutri-Nano Alpha Lipoic Acid", "Alpha Lipoic Acid"),
        ("Aquamin F", "Calcium"),
        ("Aquamin TG", "Calcium"),
        ("Sucrase", "Digestive Enzymes"),
        ("Protease, Fungal", "Digestive Enzymes"),
        ("Tolerase G", "Digestive Enzymes"),
        ("Astralagus", "Astragalus"),
        ("Buffalo Liver Concentrate", "Organ Extracts"),
        ("Green Peppers", "Green Bell Pepper"),
        ("Gardenia fruit extract", "Gardenia"),
        ("Glehnia root extract", "Glehnia"),
        ("Apricot seed extract", "Apricot"),
        ("Methyliberine", "Methylliberine"),
        ("CoreBiome Tributyrin", "Butyric Acid"),
        ("OpiTAC Glutathione", "Glutathione"),
        ("Lactium", "Casein Hydrolysate"),
        ("Cycloastragenol", "Cycloastragenol"),
        ("Senactiv", "Ginseng"),
        ("Dymethazine", "Dymethazine"),
        ("Laxosterone", "5a-Hydroxy Laxogenin"),
        ("Scullcap", "Skullcap"),
        ("Licorice (Glycyrrhiza glabra) root and rhizome extract", "Licorice"),
        ("Ashwagandha (Withania somnifera) root 15:1 extract", "Ashwagandha"),
        ("Black Cohosh (Actaea racemosa) root & rhizome extract", "Black Cohosh"),
        ("Stinging Nettle (Urtica dioica) root 10:1 extract", "Stinging Nettle"),
        ("Green Tea ext.", "Green Tea"),
        ("Gingko leaf extract", "Ginkgo"),
        ("Leucoselect Grape seed extract", "Grape Seed"),
        ("Noni 4:1 extract", "Noni"),
        ("SDG", "Lignans"),
        ("Piper longum fruit extract", "Long Pepper"),
        ("Bacopa monnieri Whole Herb Extract", "Bacopa"),
        ("Acai Berry Whole Fruit Extract", "Acai"),
        ("Cissus quadrangularis Stem Extract", "Winged Treebine"),
        ("BioVin", "Resveratrol"),
        ("Phase 2", "Common Bean Extract"),
        ("Vitashine", "Vitamin D"),
        ("California Poppy extract", "California Poppy"),
        ("Chinese Salvia", "Danshen"),
        ("Gamma Carotene", "Vitamin A"),
        ("Full Strength Pancreatin", "Digestive Enzymes"),
        ("Yaeyama Chlorella", "Chlorella"),
        ("l3C", "Diindolylmethane"),
        ("Gymnemic Acid", "Gymnema Sylvestre"),
        ("Female Hops cone extract", "Hops"),
        ("TryptoGold", "L-Tryptophan"),
        ("Trachea", "Organ Extracts"),
        ("Ovarian Tissue", "Organ Extracts"),
        ("Sodium Succinate", "Succinic Acid"),
        ("Lagerstroemia speciosa leaf extract", "Corosolic Acid"),
        ("GliSODin", "Superoxide Dismutase"),
        ("Zembrin", "Mesembrine"),
        ("Xanthoparmelia scabrosa", "Xanthoparmelia"),
        ("Yeast Fermentate, Dried", "yeast fermentate"),
        ("EpiCor dried Yeast Fermentate", "yeast fermentate"),
        ("Soynatto Fermented Soyfood", "Isoflavones"),
        ("MaquiBright Aristotelia chilensis berry standardized extract", "Maqui"),
        ("EVNolMax", "Vitamin E"),
        ("ERr 731", "Rhaponticin"),
        ("Ceramide-PCD", "Ceramides"),
        ("Tribulosides", "Tribulus"),
        ("Blue Vervain", "Blue Vervain"),
        ("Paeoniflorin", "paeoniflorin"),
        ("Isovitexin", "isovitexin"),
        ("Gamma-Butyrobetaine Hydrochloride", "gamma-butyrobetaine"),
        ("Gamma-Glutamylcysteines", "Glutathione"),
        ("GKG", "gkg"),
        ("A-KIC", "a-kic"),
        ("2-Beta Coxatene", "2-beta coxatene"),
        ("Sunvitol", "Vitamin E"),
        ("N-Methyl-D-Aspartic Acid", "n-methyl-d-aspartic acid"),
        ("Enzopharm(R) Plus", "enzopharm"),
        ("ATPro", "atpro"),
        ("Mitopure Urolithin A", "Urolithin A"),
        ("Phytopin", "Pine Bark"),
        ("PhytoSure", "phytosure"),
        ("Peat extract", "peat extract"),
        ("Oat", "Oat (Generic)"),
        ("Willow", "White Willow Bark"),
        ("Sirtmax", "Kaempferia"),
        ("Lactotripeptides", "lactotripeptides"),
        ("FRAC(R)", "frac(r)"),
        ("EP107", "ep107"),
        ("DNF-10 Yeast Hydrolysate", "Yeast Fermentate"),
        ("Cyplexinol", "cyplexinol"),
        ("AC-11", "Cat's Claw Bark"),
        ("Propionyl L-Carnitine", "L-Carnitine"),
        ("Prebiotic FOS", "Prebiotics"),
        ("N, N-Dimethyl Glycine HCl", "dimethyl glycine"),
        ("Inositol Nicotinate", "Vitamin B3"),
        ("Niacin Niacinamide & Inositol Hexanicotinate", "Vitamin B3"),
        ("L-Theanine Suntheanine", "L-Theanine"),
        ("L-Glutamic Acid HCl", "L-Glutamic Acid"),
        ("Silicic Acid", "Silicon"),
        ("Magnesio", "Magnesium"),
        ("Porcine (Sus scrofa) Bone Marrow", "Organ Extracts"),
        ("Mammary", "Organ Extracts"),
        ("Mastic tree", "Mastic Gum"),
        ("Macapure", "Maca"),
        ("MacaPure Maca extract", "Maca"),
        ("Maca 0.6% extract", "Maca"),
        ("Milk Thistle powdered extract", "Milk Thistle"),
        ("Milk Thistle Fruit and Seed Extract", "Milk Thistle"),
        ("Pycrinil Artichoke extract", "Cynarin"),
        ("Pueraria mirifica extract", "Pueraria Mirifica"),
        ("Oat Aerial Parts Extract", "Oat Straw"),
        ("Motherwort Aerial Parts Extract", "Motherwort"),
        ("Mojave Yucca root extract", "Yucca"),
        ("Mate leaf extract", "Yerba Mate"),
        ("Laminaria digitata", "Kelp"),
        ("Ivy Leaf Extract", "Ivy"),
        ("Linden", "Linden"),
        ("Neumentix", "Spearmint"),
        ("NEM Natural Eggshell Membrane", "nem"),
        ("Mythocondro", "mythocondro"),
        ("Mobilee", "mobilee"),
        ("Mirtogenol", "Bilberry"),
        ("Minor Cannabinoids", "minor cannabinoids"),
        ("Micronized Purified Flavonoid Fraction", "Diosmin"),
        ("ReceptoMax Precision Release Profile", "receptomax precision release profile"),
        ("Syntol Digestive Yeast Cleanse", "syntol digestive yeast cleanse"),
        ("True Food Superpotency Soyagen", "true food superpotency soyagen"),
        ("ImmunoLin", "immunolin"),
        ("L-Arabinose", "Arabinose"),
        ("Sarcosine", "sarcosine"),
        ("Rutaecarpine", "rutaecarpine"),
        ("Marine Chondroitin Sulphate", "Chondroitin"),
        ("Huperzine", "Huperzine A"),
        ("Horsetail leaf extract", "Horsetail"),
        ("Horsetail leaf & stem extract", "Horsetail"),
        ("Horsetail (Equisetum arvense) 4:1 aerial parts extract", "Horsetail"),
        ("Horse Chestnut 20% extract", "Aescin"),
        ("Holy Basil (Ocimum sanctum) leaf supercritical CO2 extract", "Holy Basil"),
        ("Hawthorn berry ext.", "Hawthorn"),
        ("Guggul ext.", "Guggul"),
        ("Guggulipid Gum Extract", "Guggul"),
        ("Green Tea leaf 50% extract", "Green Tea"),
        ("Green Tea Leaf Extract, Aqueous", "Green Tea"),
        ("Grape 95% extract", "Grape"),
        ("Ginkgold", "Ginkgo"),
        ("Ginkgoflavonglycosides", "Ginkgo"),
        ("Garcinia cambogia Super CitriMax clinical strength", "Garcinia Cambogia"),
        ("FruiteX-B PhytoBoron", "Boron"),
        ("ChromeMate CM-100M", "Chromium"),
        ("ChromeMate CM-100", "Chromium"),
        ("Chromax Chromium Picolinate", "Chromium"),
        ("Coenzyme Vitamin B2", "Riboflavin"),
        ("Cinnamon Bark Extract, Dried", "Cinnamon"),
        ("Chili Fruit, Seed Extract", "Capsaicin"),
        ("Chicken Collagen", "Collagen"),
        ("Chastetree berry extract", "Chasteberry"),
        ("Chaste Berry Fruit Extract", "Chasteberry"),
        ("Conjugated Bile Acid", "conjugated bile acid"),
        ("Collinsonia root PE", "Stoneroot"),
        ("CogniBoost", "cogniboost"),
        ("Cocoabuterol", "cocoabuterol"),
        ("Cowslip", "Cowslip"),
        ("Diatomaceous Earth", "diatomaceous earth"),
        ("DHQVital Dihydroquercetin", "dhqvital dihydroquercetin"),
        ("Dihydroquercetin-3-Rhamnoside", "Taxifolin"),
        ("ETAS", "etas"),
        ("Ecoganic Super Fruits", "ecoganic super fruits"),
        ("Emothion", "Glutathione"),
        ("Ergogen-XT", "ergogen"),
        ("Eurypeptides", "Tongkat Ali"),
        ("Flavanols", "flavanols"),
        ("GBBGO", "gbbgo"),
        ("Glycosaponins", "glycosaponins"),
        ("Immune Support Response", "immune support response"),
        ("Glucanase", "Digestive Enzymes"),
        ("Chinese Cinnamon (Cinnamomum cassia) bark powder", "Cinnamon"),
        ("Camu Camu Fruit Extract", "Vitamin C"),
        ("Calcium Glycinate", "Calcium"),
        ("Boswellin Super", "Boswellia"),
        ("Boswella extract", "Boswellia"),
        ("Bioperine Nature’s Thermonutrient", "Piperine"),
        ("Bilberry Berry Extract", "Bilberry"),
        ("Capros", "Amla"),
        ("AlphaSize", "Alpha GPC"),
        ("Acetyl L Carnitine Hydrochloride", "L-Carnitine"),
        ("Bovine (Bos taurus) Placenta", "Organ Extracts"),
        ("Bovine (Bos taurus) Lymph", "Organ Extracts"),
        ("CQR-300 Cissus quadrangularis stem and leaf extract", "Winged Treebine"),
        ("Buchu leaves 4:1 extract", "Buchu"),
        ("Broccoli Seed, Sprout Extract", "Broccoli"),
        ("Broccoli Bud, Stem Extract", "Broccoli"),
        ("Broccoli (Brassica oleracea) floret and stalk concentrate", "Broccoli"),
        ("Boneset aerial parts extract", "Boneset"),
        ("Blackcurrant freeze-dried extract", "Black Currant"),
        ("Black Tea leaves extract", "Black Tea"),
        ("Calcium Glycerophosphate", "calcium glycerophosphate"),
        ("Calcium Caprylate", "calcium caprylate"),
        ("Crominex 3+", "chromium"),  # Now maps via IQM alias → chromium parent
        ("Beta-Ecdysterone", "Ecdysterones"),
        ("Carotene, Natural", "carotene, natural"),
        ("Malate", "malate"),
        ("Lactococcus lactis strain plasma", "Probiotics"),
        ("Benegut Perilla Leaf Extract", "Perilla"),
        ("Bacosides A & B", "Bacopa"),
        ("Avocado/Soy Unsaponifiables", "avocado/soy unsaponifiables"),
        ("Anti-Fungi 11X-88", "anti-fungi 11x-88"),
        ("Anti-Fungi 10X-88", "anti-fungi 10x-88"),
        ("Andrographis aerial extract", "Andrographis"),
        ("Andrograph extract", "Andrographis"),
        ("Amla whole fruit powder", "Amla"),
        ("Alpha-Glycosyl Isoquercitrin", "Quercetin"),
        ("ActivAMP Gynostemma pentaphyllum Extract", "Gypenosides"),
        ("Actazin", "Kiwifruit"),
        ("AMP-XT", "amp-xt"),
        ("resVida", "Resveratrol"),
        ("pTeroPure Pterostilbene", "Pterostilbene"),
        ("organic NeuroFactor whole Coffee", "Coffee Fruit"),
        ("organic Full-Spectrum Ashwagandha  root  powder", "Ashwagandha"),
        ("grassfed Liver", "Organ Extracts"),
        ("grass-fed Bovine", "Organ Extracts"),
        ("dried Noni", "Noni"),
        ("certified organic Chlorella powder", "Chlorella"),
        ("Yodo", "Iodine"),
        ("Yellow Maca Root Extract", "Maca"),
        ("Yacon", "Yacon"),
        ("XanthoForce Hops extract", "Hops"),
        ("Vitex agnus castus extract", "Chasteberry"),
        ("Watercress Aerial Parts Extract", "Watercress"),
        ("naturally-occurring Caffeine", "Caffeine"),
        ("1-Piperoylpiperidine", "Piperine"),
        ("99% pure Hemp Isolate", "hemp isolate"),
        ("L-Asparagine", "l-asparagine"),
        ("Oleamide", "oleamide"),
        ("Phloridzin", "Phlorizin"),
        ("geniVida Genistein", "Genistein"),
        ("Uridine-5'-Monophosphate Heptahydrate Disodium", "Uridine"),
        ("Triacetyluridine", "Uridine"),
        ("Tiamina", "Vitamin B1"),
        ("ZinMax", "Zinc"),
        ("certified organic AlgaeCal", "Calcium"),
        ("acid-stable Protease", "Digestive Enzymes"),
        ("acid stable Protease", "Digestive Enzymes"),
        ("Vanadium Glycinate", "Vanadyl Sulfate"),
        ("Total Beta Glucan", "Beta-Glucan"),
        ("Super CitriMax Garcinia extract", "Garcinia"),
        ("Sulphoraphane", "Sulforaphane"),
        ("St. John’s Wort", "St. John's Wort"),
        ("St. John's Wort Flower, Leaf Extract", "St. John's Wort"),
        ("St. John's Wort Flower Head Extract", "St. John's Wort"),
        ("VitaCholine", "Choline"),
        ("WellTrim iG (IGOB131) African Mango (Irvingia gabonensis) seed extract", "African Mango"),
        ("Wild Yam (Dioscorea opposita) rhizome standardised extract", "Wild Yam"),
        ("whole Oranges", "Orange"),
        ("240 mg whole Oranges", "Orange"),
        ("organic Mimosa pudica", "Mimosa pudica"),
        ("organic Cordyceps (Cordyceps militaris) fruiting body extract", "Cordyceps"),
        ("dry sprouted Barley", "Barley"),
        ("dry Wheat Grass", "Wheatgrass"),
        ("Yucca 4:1 extract", "Yucca"),
        ("Wakame powder", "Fucoidan"),
        ("Uva Ursi 3:1 extract", "Uva Ursi"),
        ("Sweet Fennel seed powder", "Fennel"),
        ("Suma root 4:1 extract", "Suma Root"),
        ("Star Anise Seed Extract", "Star Anise"),
        ("Tea Tree Oil", "Tea Tree"),
        ("total Sulfur", "total sulfur"),
    ],
)
def test_high_frequency_active_aliases_map(normalizer, name, expected_substring):
    standard_name, mapped, _ = normalizer._enhanced_ingredient_mapping(name, [])
    assert mapped is True
    assert expected_substring.lower() in str(standard_name).lower()


@pytest.mark.parametrize(
    "name",
    [
        ("wild crafted Marshmallow"),
        ("wild crafted Red Clover"),
        ("wild crafted Uva Ursi"),
    ],
)
def test_wild_crafted_prefix_normalization_maps(normalizer, name):
    standard_name, mapped, _ = normalizer._enhanced_ingredient_mapping(name, [])
    assert mapped is True
    assert standard_name


@pytest.mark.parametrize(
    "name",
    [
        ("Hydroxypropyl Methyl Cellulose"),
        ("Hydroxypropyl Methylcellulose Phthalate"),
        ("Vegetable Pullulan"),
        ("non-GMO Vegetable Glycerin"),
        ("Dicalcium Phosphate Anhydrous"),
        ("FD&C Yellow #6 Lake"),
        ("FD&C Yellow #6 Aluminum Lake"),
        ("FD&C Yellow #5 Lake"),
        ("FD&C Yellow #5 Aluminum Lake"),
        ("FD&C Blue #1 Lake"),
        ("FD&C Blue # 1"),
        ("FD&C Blue #2 Lake"),
        ("FD&C Blue #2 Aluminum Lake"),
        ("FD&C Red #40 Aluminum Lake"),
        ("FD&C Red # 40"),
        ("Methylcellulose"),
        ("Cellulose, Plant"),
        ("Vegetable Modified Cellulose"),
        ("Film Coat"),
        ("Glycerin Coating"),
        ("Methocel"),
        ("Sodium Carboxymethycellulose"),
        ("Cellulose & Glycerin Coating"),
        ("Food Grade Coating"),
        ("Vegetable Stearates"),
        ("Di Calcium Phosphate"),
        ("Dibasic Calcium Phosphate Dihydrate"),
        ("pregelatinized Corn Starch"),
        ("Microcystalline Cellulose"),
        ("Veg. Cellulose"),
        ("Hydroxypropylmethyl Cellulose"),
        ("Magnesium Vegetable Stearate"),
        ("Cab-o-sil"),
        ("Veg. Magnesium Stearate"),
        ("Vegetable-Based Coating"),
        ("aqueous-based Coating"),
        ("Triglycerides"),
        ("Blue #1 Lake"),
        ("natural Anise flavor"),
        ("Vanilla Flavor, Natural"),
        ("Oil of Peppermint"),
        ("China Wax"),
        ("Pea Starch"),
        ("Methacrylic Acid"),
        ("Alginic Acid"),
        ("Vegetable Magnesium Silicate"),
        ("Dextrates"),
        ("Glycerol Palmitostearate"),
        ("Artificial color"),
        ("Calcium Sulfate"),
        ("Tapioca Dextrose"),
        ("Dextrose Monohydrate"),
        ("Lactose Monohydrate"),
        ("Carbomer"),
        ("yellow Ochre"),
        ("Hydroxypropyl-Beta-Cyclodextrin"),
        ("natural Lithothamnion calcarea"),
        ("Lithothamnion calcarea"),
        ("Lithothamnion corallioides"),
        # hydrogenated Cottonseed oil / Sterotex NF removed — ADD_HYDROGENATED_OILS
        # intentionally dropped from harmful_additives.json (low concern for supplements)
        ("Sodium Metasilicate"),
        ("Oligosaccharides"),
    ],
)
def test_high_frequency_inactive_aliases_map(normalizer, name):
    standard_name, mapped, _ = normalizer._enhanced_ingredient_mapping(name, [])
    assert mapped is True
    assert standard_name


@pytest.mark.parametrize(
    "name",
    [
        ("Total Polyphenols"),
        ("Contains 12.5 mcg of Stabilized Allicin"),
    ],
)
def test_descriptor_rows_are_skip_classified(normalizer, name):
    # Descriptor rows are excluded in normalization flow via nutrition/label checks.
    assert normalizer._is_nutrition_fact(name) is True


def test_generic_header_token_is_skip_classified(normalizer):
    assert normalizer._should_skip_ingredient("Ingredients") is True


@pytest.mark.parametrize(
    "name",
    [
        ("from 150 mg Betaine HCl"),
        ("from 800 mg of S-Adenosyl-L-Methionine Disulfate Tosylate"),
    ],
)
def test_from_mg_spec_rows_are_skip_classified(normalizer, name):
    assert normalizer._should_skip_ingredient(name) is True


@pytest.mark.parametrize(
    "name",
    [
        ("Trace Elements"),
        ("Trace Minerals"),
        ("Herbal Extracts"),
        ("Lactic Acid Bacteria"),
        ("Ionic Sea Minerals"),
        ("Ionic Trace Minerals"),
        ("Trace Mineral concentrate"),
        ("Ultra Trace Minerals"),
        ("Niacin & Niacinamide"),
        ("Niacin and Niacinamide"),
        ("FoodState Orange Vitamin C"),
        ("Nature's C with QPower"),
        ("Futurebiotics BioAccelerators"),
        ("Bronson BioAccelerators"),
        ("Nutrilite Phytonutrient Concentrate"),
        ("Whole Food PhytoAlgae"),
        ("Food Based Nutrients"),
    ],
)
def test_routed_terms_are_not_hard_skipped(normalizer, name):
    assert normalizer._is_nutrition_fact(name) is False
    assert normalizer._should_skip_ingredient(name) is False


@pytest.mark.parametrize(
    "name",
    [
        ("Carotenoid Mix"),
        ("Carotenoid MIx"),
        ("Enzymes"),
        ("Sulfate"),
        ("Digestive Aids/Enzymes"),
        ("Bioactive Enzymes & Proteins"),
        ("Co-Nutrients"),
        ("Stomach"),
        ("Whole Food Enzymes"),
        ("Complete Digestive Support"),
        ("80 mg broccoli"),
        ("8 mg cabbage"),
        ("Proprietary Mix of Curcumin"),
        ("Nitrate"),
        ("Nitrates"),
        ("50 mg carrots"),
        ("Total Silymarin"),
        ("Macamides and Macaenes"),
        ("Passion Factors"),
    ],
)
def test_section_header_artifacts_are_skip_classified(normalizer, name):
    assert normalizer._is_nutrition_fact(name) is True


@pytest.mark.parametrize(
    "name,expected_substring",
    [
        ("Niacin & Niacinamide", "Vitamin B3"),
        ("Niacin and Niacinamide", "Vitamin B3"),
        ("Niacin/Niacinamide", "Vitamin B3"),
        ("Lactic Acid Bacteria", "Probiotics"),
        ("FoodState Orange Vitamin C", "Vitamin C"),
        ("Nature's C with QPower", "Vitamin C"),
    ],
)
def test_iqm_rerouted_terms_map_to_conservative_forms(normalizer, name, expected_substring):
    standard_name, mapped, _ = normalizer._enhanced_ingredient_mapping(name, [])
    assert mapped is True
    assert expected_substring.lower() in str(standard_name).lower()


@pytest.mark.parametrize(
    "name",
    [
        ("Herbal Extract"),
        ("Ionic Sea Minerals"),
        ("Ionic Trace Minerals"),
        ("Trace Mineral concentrate"),
        ("Ultra Trace Minerals"),
        ("Futurebiotics BioAccelerators"),
        ("Bronson BioAccelerators"),
        ("Nutrilite Phytonutrient Concentrate"),
        ("Whole Food PhytoAlgae"),
        ("Food Based Nutrients"),
        ("InnoSlim"),
        ("S7"),
        ("Spectra"),
        ("Source-70"),
        ("elevATP"),
        ("Oxi-fend"),
        ("CyanthOx 30"),
        ("EstroG-100"),
        ("ViNitrox"),
        ("Seditol"),
        ("VitaBerry"),
        ("Dermaval"),
        ("Olea-Pro"),
        ("BioCore Optimum Complete"),
        ("Grapefruit Fiber"),
        ("Kefir Starter Culture R0215"),
        ("Fortify Optima"),
        ("HerbaFlor"),
        ("Vitamin F"),
        ("water and vegan Capsule"),
        ("Targeted release capsule"),
        ("Capsules of plant origin"),
        ("Vegan Capsules"),
        ("Vege capsule"),
        ("DRcaps Vegetable Capsule"),
        ("HPMC Vegetable Capsule"),
        ("Plant-Based Hypromellose Capsules"),
        ("organic Nu-Mag"),
        ("Nu-Mag"),
        ("Nu-Rice"),
        ("NuFlow"),
        ("CyLoc"),
        ("PAK"),
        ("AgeLoss Female Factors"),
        ("AgeLoss Male Factors"),
        ("Ecoganic Veggies & Greens"),
        ("Ecoganic Herbs & Superfoods"),
        ("Additional Foods & Extracts"),
        ("Detoxification & Liver Support"),
        ("active Flavonols, Flavonones, Flavones & Naringen"),
        ("Test 1700 Activator"),
        ("Shen Min Herb"),
        ("Charcoal, Activated"),
        ("Dicalcium Phopshate"),
        ("Pregelantinized Corn Starch"),
        ("Natural Flavouring"),
        ("natural Cherry flavour"),
        ("organic Soy Bean fiber"),
        ("Egg Albumin"),
        ("Calcium Caseinate"),
        ("Plasacryl"),
        ("Invetek chewable base"),
        ("fermentation-activated organically grown whole Soya"),
        ("enzyme pre-digested whole Soya"),
        ("high quality Protein"),
        ("Aorta"),
        ("Brain"),
        ("Pineal"),
        ("Wheat Bran"),
        ("Sustained Energy Support"),
        ("Sendara"),
        ("The Fiber Expert"),
        ("Plant-Gest Support"),
        ("Amino Acid Triplex"),
        ("PerfectAmino"),
        ("ENT-12(TM)"),
        ("BetaTOR"),
        ("Masquelier's Original OPCs"),
        ("KoAct Calcium Collagen Chelate"),
        ("InSea2"),
        ("BlueActiv"),
        ("PectaSol-C"),
        ("GlucosaGreen"),
        ("Peak02"),
        ("Arrowroot"),
        ("CARE4U"),
        ("Calzbone"),
        ("Hexadrone"),
        ("Vinegar"),
        ("Sodium Caprylate"),
        ("Magnesium Caprylate"),
        ("Ursolic & Oleanolic Acids"),
        ("New Zealand grassfed Bone Marrow"),
        ("Salmon Nasal Cartilage powder"),
        ("edible Hemoglobin"),
    ],
)
def test_descriptor_terms_map_via_other_ingredients_identity(normalizer, name):
    ing = {
        "name": name,
        "quantity": [{"quantity": 10, "unit": "mg"}],
        "unit": "mg",
        "forms": [],
    }
    result = normalizer._process_single_ingredient_enhanced(ing, is_active=True)
    assert result is not None
    assert result["mapped"] is True


@pytest.mark.parametrize(
    "name,expected_substring",
    [
        ("ERr 731 Siberian Rhubarb (Rheum rhaponticum L.) extract", "Rhaponticin"),
        ("Capros Amla extract", "Amla"),
        ("Amla (Emblica officinalis) fruit 5:1 extract", "Amla"),
        ("Black Elder Fruit Extract", "Elderberry"),
        ("Soy Isoflavones 40%", "Isoflavones"),
        ("Japanese Chlorella", "Chlorella"),
        ("BaCognize Ultra Bacopa extract", "Bacopa"),
        ("BroccoVital Myrosinase Broccoli extract", "Sulforaphane"),
        ("Deer Antler horn powder", "Deer Antler"),
        ("Deglycyrrhized Licorice", "Licorice"),
        ("Bilberry standardized extract", "Bilberry"),
        ("Ginkgo [leaf] 50:1 Extract", "Ginkgo"),
        ("Ginkgo Biloba 4:1 Extract", "Ginkgo"),
        ("Rutin NF", "Citrus Bioflavonoids"),
        ("Vegetable Oil Phytosterols", "Phytosterols"),
        ("Plant Phytosterols", "Phytosterols"),
        ("Sitosterol", "Phytosterols"),
        ("L5-MTHF", "Vitamin B9"),
        ("Levomefolate Calcium", "Vitamin B9"),
        ("New-Gar Aged Garlic bulb extract", "Garlic"),
        ("Acetyl-L-Carnitine HCI", "L-Carnitine"),
        ("L-Carnitine HCl", "L-Carnitine"),
        ("ProteaseGL", "Digestive Enzymes"),
        ("Pancreatin 5X", "Digestive Enzymes"),
        ("DigeZyme", "Digestive Enzymes"),
        ("Beta Glucan 3/6/9", "Beta-Glucan"),
        ("Daidzen", "Daidzein"),
        ("Red Clover leaf & stem extract", "Red Clover"),
        ("Bulgarian Tribulus", "Tribulus"),
        ("SDG Flax lignans", "Lignans"),
        ("Arjuna (Terminalia arjuna) bark 5:1 extract", "Arjuna"),
        ("Quercetin Anhydrous", "Quercetin"),
        ("GreenSelect Green Tea Phytosome", "Green Tea"),
        ("Saw Palmetto 45% extract", "Saw Palmetto"),
        ("Hydrolyzed Type II Collagen", "Collagen"),
        ("Bifidobacterium longum longum 35624", "Bifidobacterium Longum"),
        ("LongJaX 20:1 extract", "Tongkat Ali"),
        ("BCM-95 Curcugreen", "Curcumin"),
        ("BCM-95 Bio-Curcumin", "Curcumin"),
        ("Horsetail Grass", "Horsetail"),
        ("AlphaSize Alpha-Glyceryl Phosphoryl Choline", "Alpha GPC"),
        ("Anise 4:1 extract", "Anise"),
        ("Nettles leaf powder", "Stinging Nettle"),
        ("KSM-66 Full-Spectrum Ashwagandha root extract", "Ashwagandha"),
        ("Ashwagandha root & leaf extract", "Ashwagandha"),
        ("Shoden Ashwagandha extract", "Ashwagandha"),
        ("Eurycoma Longjack root extract", "Tongkat Ali"),
        ("K-2", "Vitamin K"),
        ("Devil's Claw 5% extract", "Devil's Claw"),
        ("Amla 4:1 extract", "Amla"),
        ("Creatine Alpha-Ketoglutarate", "Creatine"),
        ("Psyllium Husks", "Psyllium"),
        ("Rhodiola rosea root 3% extract", "Rhodiola"),
        ("Aloe vera gel powder 200:1 concentrate", "Aloe Vera"),
        ("L-5 Methyltetrahydrofolate Calcium Salt", "Vitamin B9"),
        ("Gar-O-Lic Garlic concentrate", "Garlic"),
        ("Licorice root 4:1 extract", "Licorice"),
        ("Policosanol (Saccharum officinarum) dried extract", "Policosanol"),
        ("Brown Flax", "Flaxseed"),
        ("Biotin Pure", "Biotin"),
        ("Beta Phenylethylamine", "Phenylethylamine"),
        ("GlycoCarn GPLC", "L-Carnitine"),
        ("Cereboost American Ginseng (Panax quinquefolius) extract", "Ginseng"),
        ("Monterey Pine (Pinus radiata) extract", "Pine Bark"),
        ("Optimized Curcumin extract", "Curcumin"),
        ("Keto Krill Oil", "Omega-3"),
        ("Cinnamon bark 10:1 extract", "Cinnamon"),
        ("Joint Shield 5-Loxin Advanced", "Boswellia"),
        ("Boswellin Forte", "Boswellia"),
        ("3-O-Acetyl-11-Keto-Beta-Boswellic Acid", "Akba"),
        ("Pyridoxal 5-Phosphate Monohydrate", "Vitamin B6"),
        ("Calcium Fructo-Borate", "Boron"),
        ("Oregano leaf supercritical CO2 extract", "Oregano"),
        ("Black Walnut unripe hulls extract", "Black Walnut"),
        ("HyaMax", "Hyaluronic Acid"),
        ("Mexican Wild Yam (Dioscorea villosa) rhizome standardised extract", "Wild Yam"),
        ("BioVin Grape extract", "Grape"),
        ("MegaNatural-BP Grape (Vitis vinifera) extract", "Grape"),
        ("MegaNatural BP Grape seed extract", "Grape"),
        ("SAMe Disulfate Tosylate", "SAMe"),
        ("Sodium R Alpha Lipoic Acid", "Alpha Lipoic Acid"),
        ("Calcium Beta-Hydroxy Beta-Methylbutyrate Monohydrate", "Methylbutyrate"),
        ("Beta Glucan 1,3", "Beta-Glucan"),
        ("Super Berberine", "Berberine"),
        ("EMIQ", "Quercetin"),
        ("Affron Eye", "Saffron"),
        ("Daidzein/Daidzin", "Daidzein"),
        ("Genistein/Genistin", "Genistein"),
        ("Siliphos Silybin Phytosome", "Milk Thistle"),
        ("Total Silybins", "Milk Thistle"),
        ("Banaba 1% extract", "Corosolic Acid"),
        ("L-Valine, Micronized", "L-Valine"),
        ("L-Isoleucine, Micronized", "L-Isoleucine"),
        ("L-Leucine, Micronized", "L-Leucine"),
        ("Butterbur 15% extract", "Butterbur"),
        ("Cordyceps 7% extract", "Cordyceps"),
        ("Paradoxine Grains of Paradise extract", "Grains of Paradise"),
        ("Pistacia lentiscus var. Chia", "Mastic"),
        ("Maitake PD-Fraction powder", "Maitake"),
        ("Desoxyrhaponticin", "Rhaponticin"),
        ("Potassium Carbonate", "Potassium"),
        ("Calcium Formate", "Calcium"),
        ("Probiotic 16 Strains", "Probiotics"),
        ("Lactobacillus gasseri CNCM I-5076", "Lactobacillus Gasseri"),
        ("Pharma GABA", "GABA"),
    ],
)
def test_high_confidence_alias_batch_maps(normalizer, name, expected_substring):
    standard_name, mapped, _ = normalizer._enhanced_ingredient_mapping(name, [])
    assert mapped is True
    assert expected_substring.lower() in str(standard_name).lower()


@pytest.mark.parametrize(
    "name,expected_substring",
    [
        ("Poria (Poria cocos) sclerotium double extract", "Poria"),
        ("Avena sativa (oat) tops extract", "Oat"),
        ("Neuravena Wild Green Oat extract", "Oat"),
        ("Bitter Melon (Momordica charantia) Fruit Extract 2:1", "Bitter Melon"),
        ("California Poppy [herb] 5:1 extract", "California Poppy"),
        ("Eleutherococcus senticosus root 50:1 extract", "Eleuthero"),
        ("Eleuthero [root] 4:1 extract", "Eleuthero"),
        ("Andrographis aerial parts ext.", "Andrographis"),
        ("Chinese Salvia Root Extract", "Danshen"),
        ("Buchu leaf 4:1 extract", "Buchu"),
        ("Butcher's Broom 10% extract", "Butcher"),
        ("Rosehip fruit extract", "Rose"),
        ("Lonicera japonica flower extract", "Honeysuckle"),
        ("Artichoke aerial extract", "Artichoke"),
        ("Artichoke fruit leaf extract", "Artichoke"),
        ("Toothed Clubmoss Leaf Extract", "Huperzine A"),
        ("Polypodium vulgar powder", "Polypodium"),
        ("Asparagus root extract", "Asparagus"),
        ("Scute root extract", "Skullcap"),
        ("Echinamide (Echinacea purpurea) extract", "Echinacea"),
        ("Olive Water extract", "Olive"),
        ("Guduchi root extract", "Tinospora"),
        ("Celery 10:1 extract", "Celery"),
        # Bitter Orange moved to banned_recalled_ingredients (RISK_BITTER_ORANGE)
        ("Huperzia serrata leaf extract", "Toothed Clubmoss"),
        ("Cape Aloe leaf latex extract", "Aloe"),
        ("Bitter Melon P.E.", "Bitter Melon"),
        ("Daucus sativus", "Carrot"),
        ("Parsnip", "Parsnip"),
        ("Nori yaki", "Nori"),
        ("Horse Chestnut ext.", "Horse Chestnut"),
        ("Polypodium vulgare ext.", "Polypodium"),
        ("Chinese Dodder Seed Extract", "Chinese Dodder"),
        ("False Unicorn", "False Unicorn"),
        ("Squaw Vine", "Squaw Vine"),
        ("Acai berry 4:1 extract", "Acai"),
        ("Acai std. concentrate", "Acai"),
        ("European Vervain", "Vervain"),
        ("Vervain whole herb powder", "Vervain"),
        ("Parsley aerial parts juice powder", "Parsley"),
        ("Andrographis EP80 (Andrographis paniculata) leaf extract", "Andrographis"),
        ("Shankhpushpi", "Shankhpushpi"),
        ("Cascara Sagrada P.E.", "Cascara"),
        ("European Ash (seed, fruit) extract", "European Ash"),
        ("Bulbine natalensis", "Bulbine"),
        ("Brassaiopsis glomerulata", "Brassaiopsis"),
        ("Jiaogulan Leaf Extract", "Jiaogulan"),
        ("Cytokine Suppress Mung Bean extract", "Mung Bean"),
        ("Venetron Rafuma leaf extract", "Apocynum"),
        ("Squash", "Squash"),
    ],
)
def test_high_confidence_botanical_alias_batch_maps(normalizer, name, expected_substring):
    standard_name, mapped, _ = normalizer._enhanced_ingredient_mapping(name, [])
    assert mapped is True
    assert expected_substring.lower() in str(standard_name).lower()
