#!/usr/bin/env python3
"""Wave 1 clinical curation: author study contexts for ten native strain identities.

Every context below was written from a PubMed title/abstract read on
2026-09-13 (PMIDs listed in READ_PMIDS). Doses are recorded only when the
abstract states them; where the retrieved abstract text lost the exponent
the dose is left unresolved. Combination studies are authored once under
one owner and joined to every component through `components`; they never
become individual-strain applicability. Null and negative results are kept.

Every context is source_verified_pending_clinical_review: nothing here can
score until a clinician flips it to clinician_approved. The registry is
normalized once to indent=2 / ensure_ascii=False on write (parsed content
is asserted identical before and after, apart from the additions).

    python3 scripts/audits/probiotic_curation_queue_2026_09_13/wave1_contexts.py
"""
from __future__ import annotations
import json, sys
from copy import deepcopy
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / "scripts"))
from studied_formulas import valid_native_study_context  # noqa: E402

REG = ROOT / "scripts/data/clinically_relevant_strains.json"
PENDING = "source_verified_pending_clinical_review"
READ_PMIDS = {
    # LGG
    "40702885", "39060543", "34546300", "38103462", "25473176", "41883407", "42477222", "40891819",
    # Bl-04
    "34927036", "34062085", "33161737",
    # NCFM and combinations
    "41998618", "33763399", "31131616", "36235651", "41379184", "35766604", "33443719", "35987956", "39842252",
    # BB536
    "38201872", "42046285", "39519413", "36792187", "42533554",
    # HN001
    "37622257", "36705702", "37642166", "40976401", "39275252", "41783815", "37614109",
    # HN019
    "29227175", "27275105", "28245559", "37078654", "40085083",
    # DE111
    "34408741", "36790091", "33671071", "33105368", "30049931", "33161736", "33462163",
    # S. boulardii
    "40865583", "41247686", "40251486", "40012609", "37942999", "40535538", "36086703", "37400812",
    "40884341", "36630947", "38458507",
}


def ctx(context_id, pmids, *, owner, scope="exact_strain", components=None, age, population, purpose,
        condition, outcomes, family, limitations, basis="unresolved", values=(), forms=(), duration=None,
        co_therapies=(), design, n=None, blinding="unreported", funding="unreported", tier, registration=None,
        comparator=None):
    for pmid in pmids:
        assert pmid in READ_PMIDS, f"PMID {pmid} was not read this session"
    row = {
        "context_id": context_id,
        "source_pmids": list(pmids),
        "identity_scope": scope,
        "components": list(components or [owner]),
        "population": {"age_group": age, "description": population},
        "purpose": purpose,
        "condition": condition,
        "dose": {"basis": basis, "unit": "CFU", "values": list(values), "dosage_forms": list(forms),
                 "duration_days": duration, "co_therapies": list(co_therapies)},
        "outcomes": [{"name": name, "hierarchy": hier, "kind": kind, "direction": direction}
                     for name, hier, kind, direction in outcomes],
        "trial_family": family,
        "limitations": list(limitations),
        "review_status": PENDING,
        "study_design": design,
        "sample_size": n,
        "blinding": blinding,
        "funding": funding,
        "source_tier": tier,
        "trial_registration": registration,
        "authored_on": "2026-09-13",
        "authoring_method": "PubMed title/abstract read; Wave 1 bounded search (guidelines, meta-analyses, RCTs)",
    }
    if comparator:
        row["comparator"] = comparator
    return owner, row


PI, SU = "patient_important", "surrogate"
LGG, BL04, NCFM, LPC37, BI07, HN019, HN001, BB536, DE111, SB = (
    "STRAIN_LGG", "STRAIN_LACTIS_BL04", "STRAIN_ACIDOPHILUS_NCFM", "STRAIN_PARACASEI_LPC37",
    "STRAIN_LACTIS_BI07", "STRAIN_LACTIS_HN019", "STRAIN_RHAMNOSUS_HN001", "STRAIN_LONGUM_BB536",
    "STRAIN_SUBTILIS_DE111", "STRAIN_SACCHAROMYCES")
M63, M16V, BB02, B420 = "STRAIN_INFANTIS_M63", "STRAIN_BREVE_M16V", "STRAIN_BIFIDUM_BB02", "STRAIN_LACTIS_B420"

CONTEXTS = [
    # ------------------------------------------------------------------ LGG
    ctx("lgg_gi_respiratory_outcomes_meta_40702885", ["40702885"], owner=LGG, age="mixed",
        population="69 RCTs of LGG supplementation; children and adults; effects more consistent in children, adult evidence limited",
        purpose="prevention", condition="gastrointestinal_and_respiratory_infections",
        outcomes=[("composite_gastrointestinal_outcomes", "primary", PI, "positive"),
                  ("diarrhea_risk", "secondary", PI, "positive"),
                  ("diarrhea_duration", "secondary", PI, "positive"),
                  ("respiratory_infection_risk", "primary", PI, "positive"),
                  ("respiratory_symptom_risk", "secondary", PI, "null"),
                  ("other_gastrointestinal_symptoms", "secondary", PI, "null")],
        family="meta_lgg_gi_respiratory_40702885", design="meta_analysis", funding="mixed", tier="B",
        registration="PROSPERO CRD42024539944",
        limitations=["Pooled RR 0.88 for composite GI outcomes is driven by diarrhea (RR 0.64); prediction intervals crossed the null for most other outcomes.",
                     "Moderate-to-high heterogeneity; certainty moderate for diarrhea and mostly low elsewhere; adult evidence limited.",
                     "Industry co-authorship (SIRIO). Pooled trials overlap the pediatric AAD guideline and pediatric pain contexts already recorded; not an independent confirmation of them.",
                     "No single studied CFU dose can be read from a meta-analysis."]),
    ctx("lgg_preterm_nec_strain_specific_meta_39060543", ["39060543"], owner=LGG, age="infant",
        population="Preterm infants in neonatal units; 5 RCTs (n=851) using LGG as the sole probiotic",
        purpose="prevention", condition="necrotizing_enterocolitis",
        outcomes=[("nec_stage_2_or_higher", "primary", PI, "positive"),
                  ("late_onset_sepsis", "secondary", PI, "null"),
                  ("mortality", "secondary", PI, "null")],
        family="meta_lgg_preterm_39060543", design="meta_analysis", tier="B", registration="PROSPERO CRD42022324933",
        limitations=["Hospital neonatal population; not a consumer supplement indication.",
                     "Observational studies showed no NEC effect; RCT pooled RR 0.50 (95% CI 0.26-0.93).",
                     "Doses vary across trials and are not stated in the abstract."]),
    ctx("lgg_icu_ventilator_pneumonia_prospect_34546300", ["34546300"], owner=LGG, age="adult",
        population="2653 critically ill adults predicted to need mechanical ventilation >= 72 h in 44 ICUs (Canada, USA, Saudi Arabia)",
        purpose="prevention", condition="ventilator_associated_pneumonia",
        basis="discrete_daily_arms", values=[2e10], forms=["enteral"],
        outcomes=[("ventilator_associated_pneumonia", "primary", PI, "null"),
                  ("other_icu_acquired_infections", "secondary", PI, "null"),
                  ("diarrhea", "secondary", PI, "null"),
                  ("mortality", "secondary", PI, "null"),
                  ("lgg_isolation_from_sterile_or_predominant_site", "secondary", PI, "negative")],
        family="prospect_icu_lgg", design="rct", n=2653, blinding="double", tier="C", registration="NCT02462590",
        limitations=["1 x 10^10 CFU twice daily (2 x 10^10/day) for a median of 9 days in ventilated ICU patients; none of 20 secondary outcomes differed.",
                     "Harm signal: L. rhamnosus isolated in a sterile site or as the predominant organism in 1.1% vs 0.1% (OR 14.02). Population-specific; not evidence about healthy consumers.",
                     "Cost-effectiveness companion analysis (PMID 36289153) found probiotics dominated by usual care."]),
    ctx("lgg_covid19_post_exposure_prophylaxis_38103462", ["38103462"], owner=LGG, age="unknown",
        population="182 US participants with household exposure to a confirmed COVID-19 case within 7 days",
        purpose="prevention", condition="covid19_post_exposure", duration=28,
        outcomes=[("illness_symptoms_within_28_days", "primary", PI, "positive"),
                  ("covid19_diagnosis_incidence", "secondary", PI, "null"),
                  ("time_to_covid19_diagnosis", "secondary", PI, "positive")],
        family="duke_lgg_covid_38103462", design="rct", n=182, blinding="double", tier="C", registration="NCT04399252",
        limitations=["Symptom incidence 26.4% vs 42.9% (p=0.02); overall COVID-19 diagnosis incidence 8.8% vs 15.4% was not significant (p=0.17).",
                     "Described by the authors as an initial study; daily CFU dose not given in the abstract."]),
    ctx("lgg_adult_ibs_open_label_vs_diet_25473176", ["25473176"], owner=LGG, age="adult",
        population="123 adults with Rome III IBS (median age 37; 73% female), Denmark",
        purpose="treatment", condition="irritable_bowel_syndrome", duration=42,
        outcomes=[("ibs_severity_score_change", "primary", PI, "null"),
                  ("ibs_quality_of_life", "secondary", PI, "null")],
        family="herlev_lgg_lowfodmap_25473176", design="rct", n=123, blinding="open", tier="D",
        comparator="normal Danish/Western diet; low-FODMAP diet as a second active arm",
        limitations=["Unblinded three-arm trial; after adjustment for baseline covariates the LGG vs normal-diet IBS-SSS reduction was not significant (32 points; p=0.20) although the unadjusted comparison was.",
                     "Dose not stated in the abstract."]),
    ctx("lgg_pediatric_functional_abdominal_pain_meta_41883407", ["41883407", "42477222"], owner=LGG, age="child",
        population="Children 4-18 y with functional abdominal pain disorders; 21 RCTs (n=1807) network meta-analysis and a 21-trial (n=1899) pairwise meta-analysis",
        purpose="treatment", condition="functional_abdominal_pain_disorders",
        outcomes=[("global_improvement_probiotics_vs_placebo", "primary", PI, "positive"),
                  ("complete_pain_resolution", "primary", PI, "positive"),
                  ("lgg_strain_level_ranking", "unresolved", PI, "positive")],
        family="meta_pediatric_fapd_2026", design="meta_analysis", tier="B", registration="PROSPERO CRD420251218779; CRD420251149947",
        limitations=["Class-level pooled effects; the LGG-specific finding is an indirect SUCRA ranking, not a pooled LGG estimate.",
                     "Certainty rated low to moderate; when success was defined by author thresholds response rates did not differ from placebo (PMID 42477222).",
                     "Overlaps the pediatric pain RCT already recorded (PMID 17229242); two meta-analyses of one evidence base count once."]),
    ctx("lgg_seasonal_allergic_rhinitis_chewable_40891819", ["40891819"], owner=LGG, age="adult",
        population="64 adults with seasonal allergic rhinoconjunctivitis under grass-pollen exposure (33 probiotic, 31 placebo; per-protocol)",
        purpose="treatment", condition="seasonal_allergic_rhinitis", duration=14, forms=["chewable tablet"],
        outcomes=[("allergic_rhinitis_symptom_control", "unresolved", PI, "positive"),
                  ("nasopharyngeal_lgg_detection", "secondary", SU, "positive"),
                  ("salivary_il4_and_nasal_il13", "secondary", SU, "positive")],
        family="antwerp_lgg_chewable_40891819", design="rct", n=64, blinding="double", tier="D",
        limitations=["Per-protocol analysis; symptom control reported within the probiotic group after 2 weeks rather than as a between-group primary endpoint.",
                     "Local (upper-airway) delivery via chewable; dose not stated in the abstract."]),
    # ---------------------------------------------------------------- Bl-04
    ctx("bl04_rhinovirus_challenge_phase2_34927036", ["34927036"], owner=BL04, age="adult",
        population="334 healthy US university-community volunteers randomized (232 analyzed); 28 days of Bl-04 or placebo then RV-A39 challenge",
        purpose="challenge", condition="experimental_rhinovirus_infection", duration=28,
        outcomes=[("rhinovirus_associated_illness", "primary", PI, "null")],
        family="bl04_rhinovirus_challenge_phase2", design="rct", n=334, blinding="double", funding="industry", tier="C",
        registration="NCT02679807",
        limitations=["Illness 56% vs 50% (p=0.34); no effect of oral Bl-04 on rhinovirus-associated illness.",
                     "This larger phase II trial does not reproduce the earlier positive challenge result already recorded (PMID 28343401).",
                     "Funded by Danisco/IFF; dose not stated in the abstract."]),
    ctx("bl04_fermented_milk_urti_haze_adults_34062085", ["34062085"], owner=BL04, age="adult",
        population="136 adults living in a haze-covered area of northern China consuming 250 g yogurt daily",
        purpose="prevention", condition="upper_respiratory_tract_infection", duration=84, forms=["fermented milk"],
        outcomes=[("common_cold_incidence", "primary", PI, "positive"),
                  ("influenza_like_illness_incidence", "secondary", PI, "positive"),
                  ("urti_duration", "secondary", PI, "positive"),
                  ("urti_severity", "secondary", PI, "positive"),
                  ("interferon_gamma_and_secretory_iga", "secondary", SU, "positive")],
        family="bright_dairy_bl04_yogurt_34062085", design="rct", n=136, funding="industry", tier="D",
        comparator="control yogurt without Bl-04",
        limitations=["Food-matrix delivery (yogurt); CFU dose not stated; single-site industry study (Bright Dairy).",
                     "Population exposed to air pollution; generalization to supplements is not established."]),
    ctx("bl04_cardiovascular_risk_markers_healthy_33161737", ["33161737"], owner=BL04, age="adult",
        population="Healthy adults 18-65 y (BMI 20-34.9), Bl-04 with or without bacteriophage cocktail arm",
        purpose="physiology", condition="cardiovascular_risk_markers", duration=28,
        outcomes=[("cardiovascular_risk_parameters", "primary", SU, "null")],
        family="csu_bl04_de111_cvd_33161737", design="rct", blinding="double", tier="D",
        limitations=["No significant change in measured CVD parameters with Bl-04 (with or without bacteriophages); the same trial's DE111 arm is recorded separately.",
                     "Dose not stated in the abstract; largely healthy population."]),
    # ----------------------------------------------------------------- NCFM
    ctx("ncfm_infant_colic_41998618", ["41998618"], owner=NCFM, age="infant",
        population="60 infants with colic, Brazil; five drops daily",
        purpose="treatment", condition="infantile_colic", basis="discrete_daily_arms", values=[1e9], forms=["drops"], duration=28,
        outcomes=[("responder_rate_day_28", "primary", PI, "null"),
                  ("responder_rate_day_14", "secondary", PI, "positive"),
                  ("daily_fussing_and_crying_time", "secondary", PI, "null"),
                  ("fecal_calprotectin", "secondary", SU, "null")],
        family="ufmg_ncfm_colic_41998618", design="rct", n=60, blinding="double", tier="C", registration="RBR-5pp4nks (retrospective)",
        limitations=["Primary endpoint not met (p=0.240); the day-14 responder signal was attenuated after correction for multiple comparisons.",
                     "Retrospectively registered."]),
    ctx("ncfm_lpc37_bl04_bi07_mdr_colonization_antibiotics_33763399", ["33763399"], owner=NCFM, scope="combination",
        components=[NCFM, LPC37, BL04, BI07], age="adult",
        population="120 hospitalized patients (mean age 78) treated 10 days with amoxicillin-clavulanate; 30-day study product",
        purpose="prevention", condition="multidrug_resistant_gut_colonization_during_antibiotics", duration=30,
        co_therapies=["amoxicillin-clavulanate 10 days"],
        outcomes=[("pseudomonas_colonization", "unresolved", SU, "positive"),
                  ("ampc_producing_enterobacteria_colonization", "unresolved", SU, "positive"),
                  ("esbl_infection_over_2_years", "secondary", PI, "positive")],
        family="mdr_colonization_wieers_2021", design="rct", n=120, blinding="double", funding="industry", tier="D",
        limitations=["Combination product (Bactiol duo); colonization on selective culture is a microbiological surrogate; the S. boulardii arm showed no significant change.",
                     "Doses per strain not stated; industry (Metagenics) co-authors."]),
    ctx("ncfm_lpc37_bl04_bi07_hn019_constipation_bloating_2wk_31131616", ["31131616"], owner=NCFM, scope="combination",
        components=[NCFM, LPC37, BL04, BI07, HN019], age="adult",
        population="156 adults with self-reported bloating and Rome III functional constipation",
        purpose="treatment", condition="functional_constipation_with_bloating", duration=14,
        outcomes=[("bloating", "primary", PI, "null"),
                  ("colonic_transit_time", "secondary", PI, "null"),
                  ("bowel_movement_frequency", "secondary", PI, "null"),
                  ("stool_consistency", "secondary", PI, "null"),
                  ("flatulence", "post_hoc", PI, "positive")],
        family="dupont_five_strain_constipation_31131616", design="rct", n=156, blinding="double", funding="industry", tier="C",
        registration="ISRCTN41607808",
        limitations=["Efficacy not shown for the primary outcome or any secondary outcome; placebo performed similarly.",
                     "Per-strain CFU (NCFM 10^10, Lpc-37/Bl-04/Bi-07 2.5x10^9, HN019 10^10 as printed) not machine-readable in the retrieved abstract; recorded as unresolved.",
                     "Post hoc flatulence signal only."]),
    ctx("bi07_lpc37_ncfm_bl04_omega3_elderly_inflammation_36235651", ["36235651"], owner=NCFM, scope="combination",
        components=[BI07, LPC37, NCFM, BL04], age="adult",
        population="76 community-dwelling elderly (median 71 y) with chronic low-grade inflammation; dual supplement with omega-3",
        purpose="treatment", condition="chronic_low_grade_inflammation", duration=56, co_therapies=["omega-3 supplement"],
        outcomes=[("hs_crp", "primary", SU, "null"),
                  ("il_10", "secondary", SU, "positive"),
                  ("valeric_acid", "secondary", SU, "positive")],
        family="orebro_probiotic_omega3_36235651", design="rct", n=76, blinding="double", funding="mixed", tier="D",
        registration="NCT04126330",
        limitations=["Proof-of-concept; primary hs-CRP not different; probiotic effect cannot be separated from omega-3 co-supplementation.",
                     "GSK Consumer Healthcare co-author; doses not stated."]),
    ctx("ncfm_lpc37_bl04_bi07_bb02_chemotherapy_diarrhea_41379184", ["41379184"], owner=NCFM, scope="combination",
        components=[NCFM, LPC37, BL04, BI07, BB02], age="adult",
        population="28 gastrointestinal cancer patients starting fluoropyrimidine/oxaliplatin/irinotecan chemotherapy",
        purpose="prevention", condition="chemotherapy_induced_diarrhea", basis="discrete_daily_arms", values=[2e10], duration=90,
        outcomes=[("grade_2_3_diarrhea", "primary", PI, "null"),
                  ("overall_diarrhea_incidence", "secondary", PI, "null")],
        family="unifesp_chemo_diarrhea_41379184", design="rct", n=28, tier="D",
        limitations=["Very small (n=28); 20 billion CFU/day is the five-strain total, not a per-strain dose.",
                     "No benefit for grade 2/3 or overall diarrhea."]),
    ctx("ncfm_bi07_post_rygb_food_addiction_35766604", ["35766604"], owner=NCFM, scope="combination",
        components=[NCFM, BI07], age="adult",
        population="101 adults after Roux-en-Y gastric bypass; 90 days from postoperative day 7; outcomes at 90 days and 1 year",
        purpose="treatment", condition="post_bariatric_binge_eating_and_food_addiction", duration=90,
        outcomes=[("food_addiction_symptoms_1_year", "primary", PI, "positive"),
                  ("binge_eating_score_1_year", "primary", PI, "positive"),
                  ("food_addiction_and_binge_eating_90_days", "secondary", PI, "null")],
        family="rygb_curitiba_ncfm_bi07", design="rct", n=101, blinding="double", tier="D",
        limitations=["Both groups improved at 90 days; the between-group difference appeared only at 1 year (p=0.037 and p=0.030).",
                     "Same Curitiba RYGB cohort as PMIDs 33443719 and 35987956; one trial family, not three confirmations. Dose not stated."]),
    ctx("ncfm_bi07_post_rygb_nutritional_metabolic_33443719", ["33443719", "35987956"], owner=NCFM, scope="combination",
        components=[NCFM, BI07], age="adult",
        population="Adults after Roux-en-Y gastric bypass; 3 months of FloraVantage or placebo from day 7",
        purpose="treatment", condition="post_bariatric_nutritional_and_metabolic_markers", duration=90,
        outcomes=[("serum_25_oh_vitamin_d", "secondary", SU, "unresolved"),
                  ("triglycerides", "secondary", SU, "unresolved"),
                  ("plasma_tmao_and_beta_hydroxybutyrate", "secondary", SU, "positive")],
        family="rygb_curitiba_ncfm_bi07", design="rct", blinding="double", tier="D",
        limitations=["Vitamin D and triglyceride changes were significant within the probiotic group only; between-group tests are not reported in the abstract.",
                     "Metabolomic differences (PMID 35987956) are surrogate outcomes from the same cohort."]),
    ctx("ncfm_hn001_lpc37_hn019_caloric_restriction_obese_men_39842252", ["39842252"], owner=NCFM, scope="combination",
        components=[NCFM, HN001, LPC37, HN019], age="adult",
        population="Men 25-44 y with obesity (BMI 30-39.9) under 30% caloric restriction; 25 analyzed per protocol of 33 randomized",
        purpose="treatment", condition="obesity_body_composition_under_caloric_restriction",
        basis="discrete_daily_arms", values=[8e9], duration=84,
        outcomes=[("body_weight_change", "primary", PI, "null"),
                  ("body_fat_change", "primary", PI, "null")],
        family="ecomi_unifesp_39842252", design="rct", n=25, blinding="double", tier="D",
        limitations=["8 billion CFU/day is the four-strain total (2 x 10^9 each); no between-group differences in weight or fat loss.",
                     "Per-protocol analysis of a small sample."]),
    # ---------------------------------------------------------------- BB536
    ctx("bb536_plasmacytoid_dendritic_cell_activation_38201872", ["38201872"], owner=BB536, age="adult",
        population="97 healthy adults (49 BB536, 48 placebo), Japan", purpose="physiology",
        condition="immune_marker_pdc_activation", duration=28,
        outcomes=[("cd86_expression_on_peripheral_pdcs", "primary", SU, "positive")],
        family="morinaga_bb536_pdc_38201872", design="rct", n=97, blinding="double", funding="industry", tier="D",
        registration="UMIN000045564",
        limitations=["Surrogate immune marker only; daily CFU not machine-readable in the retrieved abstract.",
                     "Manufacturer-conducted (Morinaga)."]),
    ctx("bb536_male_athletes_high_protein_gi_symptoms_42046285", ["42046285"], owner=BB536, age="adult",
        population="60 healthy male athletes (mean 18.6 y) consuming 70 g/day whey protein", purpose="prevention",
        condition="gastrointestinal_symptoms_on_high_protein_diet", basis="discrete_daily_arms", values=[4.6e10], duration=28,
        co_therapies=["whey protein 70 g/day"],
        outcomes=[("gastrointestinal_symptoms", "primary", PI, "null"),
                  ("diarrhea_related_score", "post_hoc", PI, "positive"),
                  ("odor_related_metabolites", "post_hoc", SU, "positive")],
        family="morinaga_bb536_athletes_42046285", design="rct", n=60, blinding="double", funding="industry", tier="D",
        limitations=["No between-group differences in the full cohort; subgroup and within-group findings are exploratory.",
                     "46 billion CFU/day measured at the start of the intervention."]),
    ctx("bb536_fermented_milk_gut_environment_39519413", ["39519413"], owner=BB536, age="adult",
        population="Healthy adults, fermented milk with or without BB536 for 17 days", purpose="physiology",
        condition="gut_microbiota_and_metabolites", duration=17, forms=["fermented milk"],
        outcomes=[("fecal_bifidobacterium_abundance", "primary", SU, "positive"),
                  ("tryptophan_and_indole_metabolites", "secondary", SU, "positive")],
        family="morinaga_bb536_fermented_milk_39519413", design="rct", blinding="double", funding="industry", tier="D",
        limitations=["Surrogate microbiota and metabolite endpoints; no clinical outcome; dose not stated in the abstract."]),
    ctx("bb536_guar_gum_auto_hsct_pilot_36792187", ["36792187"], owner=BB536, age="adult",
        population="12 patients with malignant lymphoma undergoing autologous stem-cell transplantation", purpose="prevention",
        condition="chemotherapy_gastrointestinal_toxicity_auto_hsct", co_therapies=["guar gum"],
        outcomes=[("total_parenteral_nutrition_duration", "primary", PI, "unresolved"),
                  ("grade_3_or_higher_diarrhea_duration", "secondary", PI, "unresolved")],
        family="kobe_bb536_synbiotic_36792187", design="rct", n=12, blinding="double", tier="D",
        limitations=["Pilot with 12 patients; medians reported without between-group tests (TPN 15 vs 17.5 days).",
                     "Synbiotic with guar gum; hospital population."]),
    ctx("m63_m16v_bb536_short_term_travel_42533554", ["42533554"], owner=BB536, scope="combination",
        components=[M63, M16V, BB536], age="adult",
        population="74 healthy adults traveling to Xinjiang for five days", purpose="prevention",
        condition="travel_related_symptoms_and_microbiota", duration=5,
        outcomes=[("gut_microbiota_composition_and_function", "primary", SU, "positive"),
                  ("irritability", "secondary", PI, "positive"),
                  ("fatigue", "secondary", PI, "positive"),
                  ("dizziness", "secondary", PI, "positive")],
        family="silk_road_travel_bifido_42533554", design="rct", n=74, blinding="double", tier="D",
        limitations=["Primary outcomes are microbiota composition; symptom findings are secondary and short (5 days).",
                     "Daily CFU exponent not machine-readable in the retrieved abstract."]),
    # ---------------------------------------------------------------- HN001
    ctx("hn001_b420_pregnancy_fishoil_child_allergy_37622257", ["37622257", "37642166"], owner=HN001, scope="combination",
        components=[HN001, B420], age="infant",
        population="Children of 439 women with overweight/obesity supplemented from early pregnancy to 6 months postpartum (2x2 factorial with fish oil); outcomes at 12 and 24 months",
        purpose="prevention", condition="childhood_allergic_disease", basis="discrete_daily_arms", values=[2e10],
        co_therapies=["fish oil arm in a 2x2 factorial design"],
        outcomes=[("physician_diagnosed_food_allergy", "primary", PI, "null"),
                  ("atopic_eczema", "primary", PI, "null"),
                  ("atopy", "primary", PI, "null"),
                  ("recurrent_wheezing_24_months", "secondary", PI, "positive")],
        family="turku_pregnancy_fishoil_probiotic", design="rct", n=439, blinding="double", tier="C",
        limitations=["Maternal supplementation, infant outcomes; 10^10 CFU each of HN001 and B. lactis 420 (2 x 10^10/day combined).",
                     "Only recurrent wheezing at 24 months differed (OR 0.39); allergy and atopy endpoints null.",
                     "Serum fatty-acid secondary analysis (PMID 37642166) is the same cohort."]),
    ctx("hn001_b420_pregnancy_child_overweight_36705702", ["36705702"], owner=HN001, scope="combination",
        components=[HN001, B420], age="infant",
        population="330 children of the Turku pregnancy cohort assessed at 24 months", purpose="prevention",
        condition="childhood_overweight", basis="discrete_daily_arms", values=[2e10],
        co_therapies=["fish oil arm in a 2x2 factorial design"],
        outcomes=[("overweight_odds_24_months", "secondary", PI, "positive"),
                  ("body_fat_percentage_24_months", "secondary", SU, "null")],
        family="turku_pregnancy_fishoil_probiotic", design="rct", n=330, blinding="double", tier="C",
        limitations=["Growth was a secondary outcome of the trial; same cohort as the allergy context, so not an independent trial."]),
    ctx("hn001_elderly_brain_function_encapsulation_40976401", ["40976401"], owner=HN001, age="adult",
        population="87 community-dwelling adults 60-80 y; micro-encapsulated vs non-encapsulated HN001 vs placebo", purpose="physiology",
        condition="brain_function_and_cognition_in_elderly",
        outcomes=[("resting_state_functional_connectivity", "primary", SU, "unresolved"),
                  ("processing_speed", "secondary", PI, "positive"),
                  ("short_term_memory", "secondary", PI, "null"),
                  ("anxiety_symptoms", "secondary", PI, "null"),
                  ("depression_and_perceived_stress", "secondary", PI, "null"),
                  ("sleep_quality", "secondary", PI, "null")],
        family="orebro_hn001_elderly_40976401", design="rct", n=87, blinding="double", tier="D", registration="NCT05801042",
        limitations=["The connectivity difference is between the two probiotic formulations, not versus placebo; dose not stated.",
                     "Most cognitive and mood domains unaffected."]),
    ctx("hn001_perceived_stress_happiness_39275252", ["39275252"], owner=HN001, age="adult",
        population="120 adults with mild to high perceived stress", purpose="treatment",
        condition="perceived_stress_and_wellbeing", duration=28,
        outcomes=[("oxford_happiness_questionnaire", "primary", PI, "null"),
                  ("perceived_stress_scale", "secondary", PI, "null"),
                  ("intervention_by_day_interaction", "post_hoc", PI, "positive")],
        family="fonterra_hn001_stress_39275252", design="rct", n=120, blinding="double", funding="industry", tier="D",
        limitations=["Primary comparisons not statistically significant; only post hoc interaction and sex subgroups reached significance.",
                     "Manufacturer-conducted (Fonterra); dose not stated."]),
    ctx("hn001_maternal_perinatal_mental_health_sr_41783815", ["41783815"], owner=HN001, age="adult",
        population="Pregnant and early-postpartum women without a diagnosed mental disorder; 4 RCTs (n=1342) reviewed, HN001 in one", purpose="prevention",
        condition="perinatal_depression_and_anxiety",
        outcomes=[("depressive_symptoms_epds", "primary", PI, "positive"),
                  ("anxiety_symptoms_stai6", "primary", PI, "positive")],
        family="sr_maternal_mental_health_41783815", design="systematic_review", tier="B", registration="PROSPERO CRD42024576678",
        limitations=["No pooling; the HN001 finding (EPDS MD -1.2; STAI-6 MD -1.0) rests on a single RCT with moderate risk of bias.",
                     "Small effect sizes; evidence judged limited by the reviewers."]),
    ctx("hn019_hn001_fos_immune_parameters_healthy_adults_37614109", ["37614109"], owner=HN001, scope="combination",
        components=[HN019, HN001], age="adult",
        population="106 healthy adults, China; synbiotic with fructooligosaccharide 500 mg/day", purpose="physiology",
        condition="immune_parameters_healthy_adults", duration=56, co_therapies=["fructooligosaccharide 500 mg/day"],
        outcomes=[("plasma_c_reactive_protein", "primary", SU, "null"),
                  ("interferon_gamma", "secondary", SU, "positive"),
                  ("il_10", "secondary", SU, "positive"),
                  ("stool_secretory_iga", "secondary", SU, "positive")],
        family="hubei_hn019_hn001_synbiotic_37614109", design="rct", n=106, blinding="double", tier="D",
        limitations=["Surrogate immune markers in healthy adults; CRP change p=0.088; strain exponents not machine-readable."]),
    # ---------------------------------------------------------------- HN019
    ctx("hn019_functional_constipation_dose_ranging_28d_29227175", ["29227175"], owner=HN019, age="adult",
        population="228 adults with Rome III functional constipation; two daily dose arms for 28 days", purpose="treatment",
        condition="functional_constipation", duration=28,
        outcomes=[("colonic_transit_time", "primary", PI, "null"),
                  ("pac_sym_pac_qol_bowel_function", "secondary", PI, "null"),
                  ("bowel_movement_frequency_low_frequency_subgroup", "post_hoc", PI, "positive"),
                  ("straining_low_frequency_subgroup_high_dose", "post_hoc", PI, "positive")],
        family="hn019_constipation_dupont_2018", design="rct", n=228, blinding="double", funding="industry", tier="C",
        limitations=["No differences in primary or secondary outcomes; benefit only in a post hoc subgroup with <= 3 bowel movements/week.",
                     "The two daily doses (1 x 10^9 and 1 x 10^10 as printed) are not machine-readable in the retrieved abstract; left unresolved.",
                     "Superseded for functional constipation by the larger null trials already recorded (PMIDs 39356506, 40320938)."]),
    ctx("hn019_intestinal_transit_meta_27275105", ["27275105"], owner=HN019, age="adult",
        population="Adults in 15 short-term probiotic RCTs measuring intestinal transit time (n=675); HN019 strain subgroup", purpose="treatment",
        condition="intestinal_transit_time",
        outcomes=[("intestinal_transit_time_hn019", "primary", PI, "positive")],
        family="meta_transit_miller_2016", design="meta_analysis", funding="industry", tier="B",
        limitations=["Pooled SMD 0.67 for HN019 from short-term trials; predates the two large null functional-constipation RCTs (2024, 2025).",
                     "Authors include the manufacturer (Ouwehand) and an industry-funded consultancy."]),
    ctx("hn019_elderly_cellular_immunity_meta_28245559", ["28245559"], owner=HN019, age="adult",
        population="Healthy elderly adults in 4 controlled trials", purpose="physiology",
        condition="cellular_immune_function",
        outcomes=[("pmn_phagocytic_capacity", "primary", SU, "positive"),
                  ("nk_cell_tumoricidal_activity", "primary", SU, "positive")],
        family="meta_hn019_elderly_immunity_28245559", design="meta_analysis", funding="industry", tier="B",
        limitations=["Four trials, short follow-up, single strain; surrogate immune assays, no clinical infection outcome.",
                     "Manufacturer co-authors (DuPont)."]),
    ctx("hn019_hn001_functional_constipation_vs_fibers_37078654", ["37078654"], owner=HN019, scope="combination",
        components=[HN019, HN001], age="adult",
        population="250 adults with functional constipation randomized across five arms (three fiber formulas, HN019 + HN001, placebo); 242 completed", purpose="treatment",
        condition="functional_constipation", duration=28, co_therapies=["oligosaccharides in all active arms"],
        outcomes=[("bowel_movement_frequency", "primary", PI, "null"),
                  ("bristol_stool_scale", "secondary", PI, "positive"),
                  ("defecation_straining", "secondary", PI, "null")],
        family="xian_fiber_probiotic_fc_37078654", design="rct", n=250, blinding="double", tier="D", registration="NCT04667884",
        limitations=["No time-by-group effect for frequency, stool form or straining; stool-form gains were within-arm and shared with fiber arms.",
                     "Probiotic arm also contained oligosaccharides; per-strain dose not stated."]),
    ctx("m16v_hn019_hn001_pediatric_urti_fever_duration_40085083", ["40085083"], owner=HN019, scope="combination",
        components=[M16V, HN019, HN001], age="child",
        population="128 children 28 days to 4 years with fever >= 38.5 C and upper respiratory tract infection, pediatric emergency department, Milan", purpose="treatment",
        condition="upper_respiratory_tract_infection_fever", duration=14, forms=["oral drops"],
        outcomes=[("fever_duration", "primary", PI, "positive"),
                  ("adverse_events", "secondary", PI, "null")],
        family="milan_pediatric_urti_probiotic_40085083", design="rct", n=128, blinding="double", tier="C",
        limitations=["Median fever duration 3 vs 5 days (adjusted RR 0.64); 0.5 mL daily of a three-strain mixture, CFU not stated.",
                     "Combination evidence; nothing here attributes the effect to any single strain."]),
    # ---------------------------------------------------------------- DE111
    ctx("de111_ileostomy_small_intestinal_germination_34408741", ["34408741", "36790091"], owner=DE111, age="adult",
        population="11 adults with ileostomy; crossover", purpose="physiology",
        condition="small_intestinal_spore_germination",
        outcomes=[("ileal_spore_and_vegetative_cell_recovery", "primary", SU, "positive"),
                  ("ileal_metabolite_and_protein_changes", "secondary", SU, "positive")],
        family="de111_ileostomy_deerland", design="crossover_rct", n=11, blinding="double", funding="industry", tier="D",
        limitations=["Germination and survival in ileal effluent is a physiological surrogate; it is not evidence of a clinical benefit.",
                     "Both publications come from the same 11-participant study (one trial family); dose not stated."]),
    ctx("de111_healthy_adults_immune_gi_pilot_33671071", ["33671071"], owner=DE111, age="adult",
        population="Healthy adults; 4-week pilot", purpose="physiology",
        condition="immune_and_gastrointestinal_health_markers", duration=28,
        outcomes=[("ex_vivo_anti_inflammatory_immune_cell_populations", "primary", SU, "positive"),
                  ("perceived_gastrointestinal_health", "secondary", PI, "null"),
                  ("circulating_and_fecal_inflammation_markers", "secondary", SU, "null"),
                  ("plasma_zonulin", "secondary", SU, "null")],
        family="csu_de111_immune_pilot_33671071", design="rct", blinding="double", tier="D",
        limitations=["Authors state the study may have been underpowered; only an ex vivo LPS-stimulation signal differed.",
                     "Dose not stated in the abstract."]),
    ctx("de111_blood_lipids_endothelial_function_33161737", ["33161737"], owner=DE111, age="adult",
        population="Healthy adults 18-65 y (BMI 20-34.9)", purpose="physiology",
        condition="blood_lipids_and_endothelial_function", duration=28,
        outcomes=[("total_cholesterol", "primary", SU, "positive"),
                  ("non_hdl_cholesterol", "primary", SU, "positive"),
                  ("endothelial_function", "secondary", SU, "unresolved"),
                  ("ldl_cholesterol", "secondary", SU, "null")],
        family="csu_bl04_de111_cvd_33161737", design="rct", blinding="double", tier="D",
        limitations=["Cholesterol reductions are relative to baseline (-8 mg/dL total; -11 mg/dL non-HDL); endothelial and LDL changes were trends (p=0.05-0.06).",
                     "Largely healthy population; dose not stated in the abstract."]),
    ctx("de111_female_athletes_offseason_training_33105368", ["33105368"], owner=DE111, age="adult",
        population="23 Division I female soccer and volleyball athletes; 10-week offseason resistance training", purpose="physiology",
        condition="training_adaptation_and_body_composition", basis="discrete_daily_arms", values=[5e9], duration=70,
        outcomes=[("strength_and_performance", "primary", PI, "null"),
                  ("body_fat_percentage", "secondary", SU, "positive")],
        family="lipscomb_de111_female_athletes_33105368", design="rct", n=23, tier="D",
        limitations=["No performance effect; body-fat interaction in a 23-athlete sample.",
                     "5 billion CFU/day with post-workout nutrition."]),
    ctx("de111_male_baseball_immune_hormonal_30049931", ["30049931"], owner=DE111, age="adult",
        population="25 Division I male baseball athletes; 12 weeks of offseason training", purpose="physiology",
        condition="immune_and_hormonal_markers_during_training", basis="discrete_daily_arms", values=[1e9], duration=84,
        outcomes=[("circulating_tnf_alpha", "primary", SU, "positive"),
                  ("body_composition_and_performance", "secondary", PI, "null"),
                  ("plasma_zonulin", "secondary", SU, "null"),
                  ("salivary_iga_and_igm", "secondary", SU, "null")],
        family="lipscomb_de111_baseball_30049931", design="rct", n=25, blinding="double", tier="D",
        limitations=["Only TNF-alpha differed; a single cytokine in 25 athletes is a surrogate signal."]),
    ctx("de111_daycare_children_microbiome_33161736", ["33161736"], owner=DE111, age="child",
        population="Healthy children 2-6 y attending day care; 8 weeks", purpose="physiology",
        condition="gut_microbiome_composition", duration=56,
        outcomes=[("overall_microbiome_equilibrium", "primary", SU, "null"),
                  ("alpha_diversity", "secondary", SU, "positive")],
        family="deerland_de111_daycare_33161736", design="rct", funding="industry", tier="D",
        limitations=["Microbiome surrogate only; no infection or symptom outcome; dose not stated; manufacturer-authored."]),
    ctx("de111_whey_protein_amino_acid_response_33462163", ["33462163"], owner=DE111, age="adult",
        population="22 recreationally active men and women", purpose="physiology",
        condition="plasma_amino_acid_response_to_whey", basis="discrete_daily_arms", values=[1e9], duration=28,
        outcomes=[("plasma_amino_acid_auc_after_whey", "primary", SU, "null")],
        family="lipscomb_de111_whey_33462163", design="rct", n=22, blinding="double", tier="D",
        limitations=["No effect on leucine, BCAA, EAA or total amino acid appearance."]),
    # --------------------------------------------------------- S. boulardii
    ctx("sb_h_pylori_eradication_adjunct_meta_family", ["40865583", "41247686", "40251486", "40012609"], owner=SB,
        scope="species_general", age="adult",
        population="Adults with Helicobacter pylori infection receiving bismuth quadruple or triple eradication therapy; four overlapping meta-analyses (10-19 RCTs each, up to 5036 patients)",
        purpose="treatment", condition="helicobacter_pylori_eradication_adjunct",
        co_therapies=["bismuth quadruple or clarithromycin triple eradication therapy"],
        outcomes=[("eradication_rate", "primary", PI, "positive"),
                  ("total_treatment_adverse_events", "secondary", PI, "positive"),
                  ("diarrhea_during_eradication", "secondary", PI, "positive")],
        family="meta_sb_hpylori_adjunct", design="meta_analysis", tier="B", registration="PROSPERO CRD42024549780 (PMID 40012609)",
        limitations=["Four meta-analyses of a largely shared, mostly Chinese RCT base; treated as one evidence family.",
                     "Modest effect (RR 1.08-1.12 in S. boulardii-specific analyses); dose is mass (500-1000 mg/day), not CFU, so no CFU applicability can be derived.",
                     "Species-level; strains vary or are unreported across trials."]),
    ctx("sb_cncm_i745_h_pylori_triple_therapy_gistar_37942999", ["37942999"], owner=SB, scope="species_general", age="adult",
        population="404 adults 40-64 y in the GISTAR cohort on clarithromycin triple therapy for 10 or 14 days", purpose="treatment",
        condition="helicobacter_pylori_eradication_adjunct", co_therapies=["clarithromycin, amoxicillin, esomeprazole"],
        outcomes=[("eradication_rate_itt", "primary", PI, "mixed"),
                  ("eradication_rate_per_protocol", "secondary", PI, "null"),
                  ("treatment_adverse_events", "secondary", PI, "null")],
        family="gistar_sb_37942999", design="rct", n=404, tier="C",
        limitations=["Higher ITT eradication only in the 10-day arm (70.8% vs 54.6%); per-protocol and 14-day comparisons null; adverse-event reduction lost significance after multiplicity adjustment.",
                     "500 mg CNCM I-745 twice daily (mass dose)."]),
    ctx("sb_cncm_i745_pediatric_acute_gastroenteritis_china_meta_40535538", ["40535538"], owner=SB, scope="species_general", age="child",
        population="Children with acute gastroenteritis on standard rehydration; 10 RCTs (n=1125) conducted in China", purpose="treatment",
        condition="pediatric_acute_gastroenteritis",
        outcomes=[("diarrhea_duration", "primary", PI, "positive"),
                  ("cure_rate", "secondary", PI, "positive")],
        family="meta_sb_page_china_40535538", design="meta_analysis", tier="B", registration="PROSPERO CRD42024567537",
        limitations=["All included trials were found only in Chinese databases; consultancy authorship (McFarland Consulting).",
                     "Duration reduction SMD -1.63 days; doses vary."]),
    ctx("sb_cncm_i745_vs_b_clausii_pediatric_gastroenteritis_36086703", ["36086703"], owner=SB, scope="species_general", age="child",
        population="317 children 6 months to 5 years with mild-moderate acute diarrhea, 8 centers in Argentina", purpose="treatment",
        condition="pediatric_acute_gastroenteritis", duration=5,
        outcomes=[("diarrhea_duration", "primary", PI, "positive")],
        family="argentina_sb_vs_bclausii_36086703", design="rct", n=317, tier="D",
        comparator="four-strain Bacillus clausii mixture (active comparator, no placebo)",
        limitations=["Active-comparator design: 64.6 vs 78.0 h diarrhea duration versus B. clausii, not versus placebo.",
                     "Dose not stated in the abstract."]),
    ctx("sb_adult_acute_viral_diarrhea_37400812", ["37400812"], owner=SB, scope="species_general", age="adult",
        population="46 adults with PCR-confirmed viral acute diarrhea, Mexico; 600 mg daily for 8 days", purpose="treatment",
        condition="acute_viral_diarrhea", duration=8, co_therapies=["paracetamol", "trimebutine"],
        outcomes=[("symptom_severity", "primary", PI, "null"),
                  ("patient_global_impression_of_change_day_4", "secondary", PI, "positive")],
        family="imss_sb_viral_diarrhea_37400812", design="rct", n=46, blinding="double", tier="D", registration="NCT05226052",
        limitations=["Severity unchanged; only the day-4 patient-rated improvement differed (70% vs 26%).",
                     "Small sample; 600 mg (about 1 x 10^9 per 100 mL as stated), mass dose."]),
    ctx("sb_cncm_i745_ppi_sibo_with_rifaximin_40884341", ["40884341"], owner=SB, scope="species_general", age="adult",
        population="108 adults with breath-test-confirmed SIBO on long-term proton pump inhibitors", purpose="treatment",
        condition="ppi_associated_small_intestinal_bacterial_overgrowth", duration=7, co_therapies=["rifaximin 400 mg twice daily 7 days"],
        outcomes=[("sibo_persistence_breath_test", "primary", SU, "positive"),
                  ("diarrhea_resolution", "secondary", PI, "positive"),
                  ("symptom_score_7x7", "secondary", PI, "positive")],
        family="rum_sb_rifaximin_sibo_40884341", design="rct", n=108, blinding="open", tier="D",
        comparator="rifaximin monotherapy",
        limitations=["Open comparative design; SIBO persistence is a breath-test surrogate (41.5% vs 21.8%).",
                     "500 mg CNCM I-745 twice daily (mass dose)."]),
    ctx("sb_cncm_i745_ibs_d_sibo_open_pilot_36630947", ["36630947"], owner=SB, scope="species_general", age="adult",
        population="54 adults with diarrhea-predominant IBS and SIBO (48 evaluated), Argentina; 15 days with dietary advice", purpose="treatment",
        condition="ibs_d_with_small_intestinal_bacterial_overgrowth", duration=15, co_therapies=["dietary advice in both arms"],
        outcomes=[("hydrogen_excretion_reduction", "primary", SU, "unresolved"),
                  ("ibs_severity_score", "secondary", PI, "unresolved"),
                  ("proportion_with_diarrhea", "secondary", PI, "positive")],
        family="bustos_fernandez_sb_sibo_36630947", design="rct", n=54, blinding="open", tier="D",
        limitations=["Open-label pilot; numerical differences reported without between-group statistics for the main endpoints.",
                     "Dose not stated in the abstract."]),
    ctx("sb_travelers_diarrhea_prevention_meta_38458507", ["38458507"], owner=SB, scope="species_general", age="mixed",
        population="Travelers in 10 RCTs of probiotic prophylaxis across genera", purpose="prevention",
        condition="travelers_diarrhea",
        outcomes=[("travelers_diarrhea_incidence", "primary", PI, "positive")],
        family="meta_travelers_diarrhea_38458507", design="meta_analysis", tier="B",
        limitations=["Strain-nonspecific pooled statement that S. boulardii and S. cerevisiae were effective; few trials, mixed genera, no S. boulardii-specific effect size in the abstract."]),
    ctx("sb_cncm_i745_mdr_colonization_antibiotics_33763399", ["33763399"], owner=SB, scope="species_general", age="adult",
        population="Hospitalized patients (mean age 78) on amoxicillin-clavulanate; S. boulardii CNCM I-745 arm of a three-arm trial", purpose="prevention",
        condition="multidrug_resistant_gut_colonization_during_antibiotics", duration=30, co_therapies=["amoxicillin-clavulanate 10 days"],
        outcomes=[("pseudomonas_and_ampc_colonization", "unresolved", SU, "null")],
        family="mdr_colonization_wieers_2021", design="rct", n=120, blinding="double", funding="industry", tier="D",
        limitations=["No significant colonization changes in the S. boulardii group while the four-strain mixture arm changed; same trial as the NCFM combination context.",
                     "Dose not stated."]),
]


def main():
    raw = REG.read_text()
    reg = json.loads(raw)
    before = deepcopy(reg)
    entries = {e["id"]: e for e in reg["clinically_relevant_strains"]}
    added = 0
    for owner, row in CONTEXTS:
        entry = entries[owner]
        for component in row["components"]:
            assert component in entries, (row["context_id"], component)
        assert valid_native_study_context(row, owner), f"invalid context {row['context_id']}"
        existing = entry.setdefault("study_contexts", [])
        assert all(c.get("context_id") != row["context_id"] for c in existing), f"duplicate {row['context_id']}"
        assert not any(set(c.get("source_pmids", [])) == set(row["source_pmids"]) and c.get("condition") == row["condition"]
                       for c in existing), f"same sources already authored under {owner}: {row['context_id']}"
        existing.append(row)
        added += 1
    meta = reg["_metadata"]
    meta["version"] = "2.3.0"
    meta["last_updated"] = "2026-09-13"
    meta["native_context_note_2026_09_13"] = (
        f"Wave 1 bounded curation: {added} study contexts authored for STRAIN_LGG, STRAIN_LACTIS_BL04, "
        "STRAIN_ACIDOPHILUS_NCFM, STRAIN_LONGUM_BB536, STRAIN_RHAMNOSUS_HN001, STRAIN_LACTIS_HN019, "
        "STRAIN_SUBTILIS_DE111 and STRAIN_SACCHAROMYCES (Lpc-37 and Bi-07 join through combination contexts). "
        "Every context is source_verified_pending_clinical_review; optional study_design / sample_size / blinding / "
        "funding / source_tier / trial_registration describe quality and never score. Null and negative results are kept. "
        "Publication families (trial_family) mark papers from one cohort so they cannot count as independent confirmations.")
    # Everything other than the additions must be unchanged.
    after = deepcopy(reg)
    for entry in after["clinically_relevant_strains"]:
        entry.pop("study_contexts", None)
    for entry in before["clinically_relevant_strains"]:
        entry.pop("study_contexts", None)
    for key in ("version", "last_updated", "native_context_note_2026_09_13"):
        after["_metadata"].pop(key, None); before["_metadata"].pop(key, None)
    assert after == before, "unexpected change outside study_contexts / metadata"
    REG.write_text(json.dumps(reg, indent=2, ensure_ascii=False) + "\n")
    total = sum(len(e.get("study_contexts", [])) for e in reg["clinically_relevant_strains"])
    print(f"authored {added} contexts; registry now holds {total} contexts across "
          f"{sum(1 for e in reg['clinically_relevant_strains'] if e.get('study_contexts'))} identities")


if __name__ == "__main__":
    main()
