#!/usr/bin/env python3
"""Generate per-condition and per-drug-class Markdown views of ingredient_interaction_rules.json.

Source of truth: scripts/data/ingredient_interaction_rules.json (untouched).
Output: scripts/data/views/by_condition/<condition>.md
        scripts/data/views/by_drug_class/<drug_class>.md
        scripts/data/views/pregnancy_lactation.md

Views are regenerated on every run. Do not edit them by hand.

Usage:
    python3 scripts/tools/split_rules_by_condition.py
"""
from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
RULES_PATH = REPO / "scripts" / "data" / "ingredient_interaction_rules.json"
TAXONOMY_PATH = REPO / "scripts" / "data" / "clinical_risk_taxonomy.json"
VIEWS_DIR = REPO / "scripts" / "data" / "views"
HEADER = (
    "<!-- AUTO-GENERATED by scripts/tools/split_rules_by_condition.py — do not edit. "
    "Source of truth: scripts/data/ingredient_interaction_rules.json -->\n\n"
)


def _load(path: Path) -> dict:
    return json.loads(path.read_text())


def _short(text: str | None, n: int = 140) -> str:
    if not text:
        return ""
    text = " ".join(text.split())
    return text if len(text) <= n else text[: n - 1] + "…"


def _row(rule: dict, sub: dict) -> str:
    subj = rule.get("subject_ref", {})
    sid = subj.get("canonical_id", "?")
    db = subj.get("db", "?")
    sev = sub.get("severity", "")
    ev = sub.get("evidence_level", "")
    head = _short(sub.get("alert_headline"), 80)
    mech = _short(sub.get("mechanism"), 180)
    return f"| `{sid}` | {db} | {sev} | {ev} | {head} | {mech} |"


TABLE_HEAD = (
    "| canonical_id | db | severity | evidence | alert_headline | mechanism |\n"
    "|---|---|---|---|---|---|\n"
)


def write_condition_views(rules: list[dict], conditions: list[dict]) -> int:
    by_cond: dict[str, list[tuple[dict, dict]]] = defaultdict(list)
    for r in rules:
        for cr in r.get("condition_rules", []) or []:
            cid = (cr.get("condition_id") or "").strip().lower()
            if cid:
                by_cond[cid].append((r, cr))

    out_dir = VIEWS_DIR / "by_condition"
    out_dir.mkdir(parents=True, exist_ok=True)
    valid_ids = {c["id"]: c for c in conditions if isinstance(c, dict)}

    written = 0
    for cid, items in sorted(by_cond.items()):
        meta = valid_ids.get(cid, {})
        label = meta.get("label", cid)
        items.sort(key=lambda x: x[0].get("subject_ref", {}).get("canonical_id", ""))
        body = HEADER
        body += f"# {label} ({cid})\n\n"
        body += f"**{len(items)} rules.** Category: {meta.get('category', '—')}\n\n"
        body += TABLE_HEAD
        body += "\n".join(_row(r, cr) for r, cr in items) + "\n"
        (out_dir / f"{cid}.md").write_text(body)
        written += 1
    return written


def write_drug_class_views(rules: list[dict], drug_classes: list[dict]) -> int:
    by_dc: dict[str, list[tuple[dict, dict]]] = defaultdict(list)
    for r in rules:
        for dr in r.get("drug_class_rules", []) or []:
            did = (dr.get("drug_class_id") or "").strip().lower()
            if did:
                by_dc[did].append((r, dr))

    out_dir = VIEWS_DIR / "by_drug_class"
    out_dir.mkdir(parents=True, exist_ok=True)
    valid_ids = {c["id"]: c for c in drug_classes if isinstance(c, dict)}

    written = 0
    for did, items in sorted(by_dc.items()):
        meta = valid_ids.get(did, {})
        label = meta.get("label", did)
        items.sort(key=lambda x: x[0].get("subject_ref", {}).get("canonical_id", ""))
        body = HEADER
        body += f"# {label} ({did})\n\n"
        body += f"**{len(items)} rules.** Category: {meta.get('category', '—')}\n\n"
        body += TABLE_HEAD
        body += "\n".join(_row(r, dr) for r, dr in items) + "\n"
        (out_dir / f"{did}.md").write_text(body)
        written += 1
    return written


def write_pregnancy_lactation_view(rules: list[dict]) -> None:
    items = []
    for r in rules:
        pl = r.get("pregnancy_lactation")
        if isinstance(pl, dict) and (pl.get("pregnancy_category") or pl.get("lactation_category")):
            items.append((r, pl))
    items.sort(key=lambda x: x[0].get("subject_ref", {}).get("canonical_id", ""))

    body = HEADER + "# Pregnancy & Lactation block\n\n"
    body += f"**{len(items)} rules** with an authored `pregnancy_lactation` block.\n\n"
    body += (
        "| canonical_id | preg_category | lact_category | evidence | mechanism |\n"
        "|---|---|---|---|---|\n"
    )
    for r, pl in items:
        sid = r.get("subject_ref", {}).get("canonical_id", "?")
        body += (
            f"| `{sid}` | {pl.get('pregnancy_category', '')} | {pl.get('lactation_category', '')} "
            f"| {pl.get('evidence_level', '')} | {_short(pl.get('mechanism'), 180)} |\n"
        )
    (VIEWS_DIR / "pregnancy_lactation.md").write_text(body)


def write_index(n_cond: int, n_dc: int) -> None:
    body = HEADER + "# Interaction rule views — last regeneration\n\n"
    body += "Auto-generated counts. Hand-written docs live in `README.md` (not overwritten).\n\n"
    body += f"- **{n_cond}** condition views — `by_condition/<condition>.md`\n"
    body += f"- **{n_dc}** drug-class views — `by_drug_class/<drug_class>.md`\n"
    body += "- **1** pregnancy/lactation aggregate — `pregnancy_lactation.md`\n\n"
    body += "Regenerate: `python3 scripts/tools/split_rules_by_condition.py`\n"
    (VIEWS_DIR / "REPORT.md").write_text(body)


def main() -> int:
    data = _load(RULES_PATH)
    rules = data.get("interaction_rules", [])
    tax = _load(TAXONOMY_PATH)

    n_cond = write_condition_views(rules, tax.get("conditions", []))
    n_dc = write_drug_class_views(rules, tax.get("drug_classes", []))
    write_pregnancy_lactation_view(rules)
    write_index(n_cond, n_dc)

    print(f"Wrote {n_cond} condition view(s), {n_dc} drug-class view(s) to {VIEWS_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
